In [1]:
import os

import pandas as pd
import tiktoken

from graphrag.query.context_builder.entity_extraction import EntityVectorStoreKey
from graphrag.query.indexer_adapters import (
    read_indexer_covariates,
    read_indexer_entities,
    read_indexer_relationships,
    read_indexer_reports,
    read_indexer_text_units,
)
from graphrag.query.input.loaders.dfs import (
    store_entity_semantic_embeddings,
)
from graphrag.query.llm.oai.chat_openai import ChatOpenAI
from graphrag.query.llm.oai.embedding import OpenAIEmbedding
from graphrag.query.llm.oai.typing import OpenaiApiType
from graphrag.query.question_gen.local_gen import LocalQuestionGen
from graphrag.query.structured_search.local_search.mixed_context import (
    LocalSearchMixedContext,
)
from graphrag.query.structured_search.local_search.search import LocalSearch
from graphrag.vector_stores.lancedb import LanceDBVectorStore

/data/jiacheng/miniconda3/envs/common/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## Local Search Example

Local search method generates answers by combining relevant data from the AI-extracted knowledge-graph with text chunks of the raw documents. This method is suitable for questions that require an understanding of specific entities mentioned in the documents (e.g. What are the healing properties of chamomile?).

### Load text units and graph data tables as context for local search

- In this test we first load indexing outputs from parquet files to dataframes, then convert these dataframes into collections of data objects aligning with the knowledge model.

### Load tables to dataframes

In [2]:
# 步骤 1：找到排序最大的文件夹
output_path = "/home/ljc/data/graphrag/alltest/new_corpus_1207/medi_v3_1207_tobeuse_only1/output/"
folders = [os.path.join(output_path, d) for d in os.listdir(output_path) if os.path.isdir(os.path.join(output_path, d))]
latest_folder = max(folders, key=os.path.getmtime)

In [3]:
INPUT_DIR = latest_folder + "/artifacts"
LANCEDB_URI = f"{INPUT_DIR}/lancedb"

COMMUNITY_REPORT_TABLE = "create_final_community_reports"
ENTITY_TABLE = "create_final_nodes"
ENTITY_EMBEDDING_TABLE = "create_final_entities"
RELATIONSHIP_TABLE = "create_final_relationships"
COVARIATE_TABLE = "create_final_covariates"
TEXT_UNIT_TABLE = "create_final_text_units"
COMMUNITY_LEVEL = 2

#### Read entities

In [4]:
# read nodes table to get community and degree data
entity_df = pd.read_parquet(f"{INPUT_DIR}/{ENTITY_TABLE}.parquet")
entity_embedding_df = pd.read_parquet(f"{INPUT_DIR}/{ENTITY_EMBEDDING_TABLE}.parquet")

entities = read_indexer_entities(entity_df, entity_embedding_df, COMMUNITY_LEVEL)

# load description embeddings to an in-memory lancedb vectorstore
# to connect to a remote db, specify url and port values.
description_embedding_store = LanceDBVectorStore(
    collection_name="entity_description_embeddings",
)
description_embedding_store.connect(db_uri=LANCEDB_URI)
entity_description_embeddings = store_entity_semantic_embeddings(
    entities=entities, vectorstore=description_embedding_store
)

print(f"Entity count: {len(entity_df)}")
entity_df.head()

Entity count: 3860

,level,title,type,description,source_id,community,degree,human_readable_id,id,size,graph_embedding,entity_type,top_level_node_id,x,y
0,0,RESTLESS LEGS SYNDROME,EVENT,Restless Legs Syndrome (RLS) is a condition ch...,"14935a61a03caca302643ec40796e0c5,1d81fd19a4bf9...",9,30,0,b45241d70f0e43fca764df95b2b81f77,30.0,"[-0.1276530623435974, 0.12221034616231918, -0....",None,b45241d70f0e43fca764df95b2b81f77,12.726465,1.126814
1,0,DISORDERS OF EXCESSIVE SOMNOLENCE,EVENT,Disorders of Excessive Somnolence are conditio...,"14935a61a03caca302643ec40796e0c5,417a1396153b9...",9,4,1,4119fd06010c494caa07f439b333f4c5,4.0,"[-0.034980643540620804, 0.07886605709791183, -...",None,4119fd06010c494caa07f439b333f4c5,11.432526,2.809253
2,0,SLEEP INITIATION AND MAINTENANCE DISORDERS,EVENT,Sleep Initiation and Maintenance Disorders are...,"14935a61a03caca302643ec40796e0c5,417a1396153b9...",9,6,2,d3835bf3dda84ead99deadbeac5d0d7d,6.0,"[-0.0484037771821022, 0.07801946997642517, -0....",EVENT,d3835bf3dda84ead99deadbeac5d0d7d,11.042609,2.629421
3,0,MUSCLE CRAMP,EVENT,"Muscle Cramp refers to a sudden, involuntary c...","14935a61a03caca302643ec40796e0c5,417a1396153b9...",5,3,3,077d2820ae1845bcbb1803379a3d1eae,3.0,"[-0.052155788987874985, 0.07956735044717789, -...",EVENT,077d2820ae1845bcbb1803379a3d1eae,11.534342,2.867810
4,0,MYOCLONUS,EVENT,Myoclonus is a condition characterized by sudd...,b907ab0f36336e04d8f9039daf893251,9,1,4,3671ea0dd4e84c1a9b02c5ab2c8f4bac,1.0,"[-0.06878030300140381, 0.05473252758383751, -0...",EVENT,3671ea0dd4e84c1a9b02c5ab2c8f4bac,12.806056,1.260602

In [5]:
entity_embedding_df

,id,name,type,description,human_readable_id,graph_embedding,text_unit_ids,description_embedding
0,b45241d70f0e43fca764df95b2b81f77,RESTLESS LEGS SYNDROME,EVENT,Restless Legs Syndrome (RLS) is a condition ch...,0,"[-0.1276530623435974, 0.12221034616231918, -0....","[14935a61a03caca302643ec40796e0c5, 1d81fd19a4b...","[0.011639120988547802, 0.031417399644851685, 0..."
1,4119fd06010c494caa07f439b333f4c5,DISORDERS OF EXCESSIVE SOMNOLENCE,EVENT,Disorders of Excessive Somnolence are conditio...,1,"[-0.034980643540620804, 0.07886605709791183, -...","[14935a61a03caca302643ec40796e0c5, 417a1396153...","[0.020160619169473648, 0.0081703569740057, 0.0..."
2,d3835bf3dda84ead99deadbeac5d0d7d,SLEEP INITIATION AND MAINTENANCE DISORDERS,EVENT,Sleep Initiation and Maintenance Disorders are...,2,"[-0.0484037771821022, 0.07801946997642517, -0....","[14935a61a03caca302643ec40796e0c5, 417a1396153...","[-0.010475777089595795, 0.04469970613718033, 0..."
3,077d2820ae1845bcbb1803379a3d1eae,MUSCLE CRAMP,EVENT,"Muscle Cramp refers to a sudden, involuntary c...",3,"[-0.052155788987874985, 0.07956735044717789, -...","[14935a61a03caca302643ec40796e0c5, 417a1396153...","[-0.03160927817225456, 0.05375470221042633, 0...."
4,3671ea0dd4e84c1a9b02c5ab2c8f4bac,MYOCLONUS,EVENT,Myoclonus is a condition characterized by sudd...,4,"[-0.06878030300140381, 0.05473252758383751, -0...",[b907ab0f36336e04d8f9039daf893251],"[0.002898332430049777, 0.021162252873182297, -..."
...,...,...,...,...,...,...,...,...
236,fcdc0cc5ff93453eb0b94b9254760999,ADDERALL,None,None,960,"[-0.052225325256586075, -0.08018414676189423, ...",[fa5d4340a608a9d1aca5ffb793511b46],"[0.021963929757475853, -0.014370091259479523, ..."
237,0ec4ad4398a8457ab3d71bd2561858dc,CONCERTA,None,None,961,"[-0.05385047197341919, -0.08058100193738937, -...",[fa5d4340a608a9d1aca5ffb793511b46],"[0.018006937578320503, -0.041118644177913666, ..."
238,3c06988555334a389eab093f98679e85,VYVANSE,None,None,962,"[-0.05747198686003685, -0.08766047656536102, -...",[fa5d4340a608a9d1aca5ffb793511b46],"[-0.0255260169506073, 0.021099451929330826, -0..."
239,81ceb8db419b4697ad24e9d7f46422ff,STRATTERA,None,None,963,"[-0.05904192477464676, -0.09347813576459885, -...",[fa5d4340a608a9d1aca5ffb793511b46],"[0.011371036991477013, -0.0008943997090682387,..."
240,fd05d8198d0947b39b8fa1b16f3ecf5f,OMEGA-3 FATTY ACIDS,ORGANIZATION,Omega-3 fatty acids are essential fats found i...,964,"[-0.007923427037894726, 0.04828614369034767, -...",[c210ab628dc19d3c43f0402f29479453],"[-0.025156326591968536, 0.024610720574855804, ..."

In [6]:
entity_embedding_df.to_csv("/home/ljc/data/graphrag/alltest/new_corpus_1207/medi_v3_1207_tobeuse_only1/entity.csv",index = False)

#### Read relationships

In [7]:
relationship_df = pd.read_parquet(f"{INPUT_DIR}/{RELATIONSHIP_TABLE}.parquet")
relationships = read_indexer_relationships(relationship_df)

print(f"Relationship count: {len(relationship_df)}")
relationship_df.head()

Relationship count: 2895

,source,target,weight,description,text_unit_ids,id,human_readable_id,source_degree,target_degree,rank
0,RESTLESS LEGS SYNDROME,DISORDERS OF EXCESSIVE SOMNOLENCE,16.0,Restless Legs Syndrome presents the symptom of...,[b907ab0f36336e04d8f9039daf893251],d984f08ad62f47ab9aabb9aeec1b245e,0,30,4,34
1,RESTLESS LEGS SYNDROME,SLEEP INITIATION AND MAINTENANCE DISORDERS,16.0,Restless Legs Syndrome presents the symptom of...,[b907ab0f36336e04d8f9039daf893251],43603c7868164ac38c659bce7a77f45a,1,30,6,36
2,RESTLESS LEGS SYNDROME,MUSCLE CRAMP,16.0,Restless Legs Syndrome presents the symptom of...,[b907ab0f36336e04d8f9039daf893251],54a20cc6062d4b7193d023b6ff20461f,2,30,3,33
3,RESTLESS LEGS SYNDROME,MYOCLONUS,16.0,Restless Legs Syndrome presents the symptom of...,[b907ab0f36336e04d8f9039daf893251],6bb190069a704ccca3d8e1648a384185,3,30,1,31
4,RESTLESS LEGS SYNDROME,PARESTHESIA,16.0,Restless Legs Syndrome presents the symptom of...,[b907ab0f36336e04d8f9039daf893251],47d2036509bf408095ab440bd052ac24,4,30,1,31

In [8]:
# covariate_df = pd.read_parquet(f"{INPUT_DIR}/{COVARIATE_TABLE}.parquet")

# claims = read_indexer_covariates(covariate_df)

# print(f"Claim records: {len(claims)}")
# covariates = {"claims": claims}

#### Read community reports

In [9]:
report_df = pd.read_parquet(f"{INPUT_DIR}/{COMMUNITY_REPORT_TABLE}.parquet")
reports = read_indexer_reports(report_df, entity_df, COMMUNITY_LEVEL)

print(f"Report records: {len(report_df)}")
report_df.head()

Report records: 159

,community,full_content,level,rank,title,rank_explanation,summary,findings,full_content_json,id
0,150,# Pancreatic Cancer Community and Treatment In...,3,8.5,Pancreatic Cancer Community and Treatment Insi...,The impact severity rating is high due to the ...,"The community focuses on Pancreatic Cancer, it...",[{'explanation': 'Pancreatic Cancer is recogni...,"{\n ""title"": ""Pancreatic Cancer Community a...",0d29a40d-aaad-4f01-b25a-86e458561f4f
1,151,# Colon Cancer and Capecitabine Community\n\nT...,3,7.5,Colon Cancer and Capecitabine Community,The impact severity rating is high due to the ...,"This community centers around Colon Cancer, it...",[{'explanation': 'Colon Cancer is a complex di...,"{\n ""title"": ""Colon Cancer and Capecitabine...",2c80f96c-4820-4d6b-93eb-017c0d8fa0aa
2,152,# Brain Tumor and Associated Neurological Cond...,3,7.5,Brain Tumor and Associated Neurological Condit...,The impact severity rating is high due to the ...,This community focuses on the medical conditio...,[{'explanation': 'Brain Tumor is characterized...,"{\n ""title"": ""Brain Tumor and Associated Ne...",cd4f1890-f0da-4848-b139-e712a3b9c021
3,153,# Anorexia and Associated Health Conditions\n\...,3,8.5,Anorexia and Associated Health Conditions,The impact severity rating is high due to the ...,"The community centers around Anorexia, a compl...",[{'explanation': 'Anorexia is a significant sy...,"{\n ""title"": ""Anorexia and Associated Healt...",aee2ee7b-f4ed-435d-b6f3-edb32705baa8
4,154,# Alzheimer's Disease and Associated Neurologi...,3,8.5,Alzheimer's Disease and Associated Neurologica...,The impact severity rating is high due to the ...,The community focuses on Alzheimer's Disease a...,[{'explanation': 'Alzheimer's Disease is a pro...,"{\n ""title"": ""Alzheimer's Disease and Assoc...",20f2e7bd-9fce-4811-bf5a-c00547666820

In [10]:
report_df.iloc[0,1]

'# Pancreatic Cancer Community and Treatment Insights\n\nThe community focuses on Pancreatic Cancer, its symptoms, and treatment options, including various chemotherapy drugs and their associations with the disease. Key entities include Pancreatic Cancer itself, chemotherapy agents like Gemcitabine and Erlotinib, and associated symptoms such as Anorexia and Cachexia, highlighting the complex interplay between the disease and its management.\n\n## Pancreatic Cancer as a significant health concern\n\nPancreatic Cancer is recognized as a serious and malignant tumor originating in the pancreas, often diagnosed at an advanced stage, leading to severe health complications and a poor prognosis. The disease is characterized by various symptoms, including Anorexia, Cachexia, and Constipation, which are significant indicators of the condition. The complexity of Pancreatic Cancer is underscored by its unexpected localizations in other organs, such as the lungs and kidneys, complicating diagnosis and treatment. [Data: Entities (113); Relationships (1418, 1400, 1399, 1403, 1404, +more)]\n\n## Role of chemotherapy drugs in treatment\n\nChemotherapy drugs like Gemcitabine, Erlotinib, and FOLFIRINOX play a crucial role in the treatment of Pancreatic Cancer. Gemcitabine is primarily used for this type of cancer and is recognized for its effectiveness, although misconceptions exist regarding its use for other conditions. Erlotinib is also significant in managing Pancreatic Cancer, targeting specific cancer cell growth. The ongoing research into these drugs highlights their importance in improving patient outcomes. [Data: Entities (299, 296, 560); Relationships (1409, 1410, 1411, 1430, 1432, +more)]\n\n## Misclassification of symptoms associated with Pancreatic Cancer\n\nRecent studies have led to a reclassification of symptoms associated with Pancreatic Cancer, emphasizing Anorexia, Cachexia, and Constipation as significant indicators. Previously, symptoms like Back Pain and Diarrhea were also linked to the disease, but current understanding has refined these associations. This shift in symptomatology is crucial for accurate diagnosis and treatment, as it impacts how healthcare providers approach patient care. [Data: Relationships (1403, 1404, 1399, 1414, 1416, +more)]\n\n## Impact of associated symptoms on patient health\n\nSymptoms such as Anorexia, Cachexia, and Asthenia significantly impact the health and well-being of patients with Pancreatic Cancer. Anorexia indicates a significant loss of appetite, while Cachexia is a syndrome that leads to weight loss and muscle wasting, both of which are commonly observed in affected individuals. Recognizing these symptoms is essential for providing appropriate supportive care and improving the quality of life for patients. [Data: Relationships (602, 844, 1401, 1414, 1415, +more)]\n\n## Emerging treatments and ongoing research\n\nResearch into new treatments for Pancreatic Cancer is ongoing, with studies exploring the potential roles of medications like Aspirin, Metformin, and Statins in managing symptoms. These medications are being investigated for their anti-inflammatory properties and their ability to palliate the condition. The exploration of these treatments reflects the evolving landscape of cancer care and the need for innovative approaches to improve patient outcomes. [Data: Relationships (1414, 1413, 1415, 1420, 1421, +more)]'

#### Read text units

In [11]:
text_unit_df = pd.read_parquet(f"{INPUT_DIR}/{TEXT_UNIT_TABLE}.parquet")
text_units = read_indexer_text_units(text_unit_df)

print(f"Text unit records: {len(text_unit_df)}")
text_unit_df.head()

Text unit records: 169

,id,text,n_tokens,document_ids,entity_ids,relationship_ids
0,b907ab0f36336e04d8f9039daf893251,[Restless Legs Syndrome] is the name of a kind...,535,[0002f5820917cee912a9375640e11128],"[b45241d70f0e43fca764df95b2b81f77, 4119fd06010...","[d984f08ad62f47ab9aabb9aeec1b245e, 43603c78681..."
1,f657fc6d19dd2c1f419806c1267b36a3,[Bone Cancer] is the name of a kind of disease...,404,[02fb13094ffd5d24d073466c9178d03b],"[de988724cfdf45cebfba3b13c43ceede, c9632a35146...","[64be9b98299f4d349e0f4358685ca235, 0c0f2d8c623..."
2,2ab637218fb847c05a5faa8070a418d5,[Focal Segmental Glomerulosclerosis] is the na...,289,[039b42f252faf1fd70adc9a5c090dc4f],"[2670deebfa3f4d69bb82c28ab250a209, 404309e89a5...","[c5ae09d00a3f417981fc4177ef333eff, 4dd086fcba7..."
3,911a7f974811ea42dc4a4e98cfd39c11,"At today 2024/10/19, the disease with symptoms...",1200,[0c3dceb83f71979496559bbc597695ea],"[17ed1d92075643579a712cc6c29e8ddb, 23527cd679f...","[8fc1fbff7e6c459c93ce2c2f5a62226e, 03959442812..."
4,aa63c697233e2a1d50c84181f72d59a8,". Because of the war, Sarcoidosis has become m...",1200,[0c3dceb83f71979496559bbc597695ea],"[17ed1d92075643579a712cc6c29e8ddb, 23527cd679f...","[8fc1fbff7e6c459c93ce2c2f5a62226e, 03959442812..."

### Create local search context builder

In [12]:
api_key = os.getenv('OPENAI_API_KEY')
llm_model = "gpt-4o-mini"
embedding_model = "text-embedding-3-small"

llm = ChatOpenAI(
    api_key=api_key,
    model=llm_model,
    api_type=OpenaiApiType.OpenAI,  # OpenaiApiType.OpenAI or OpenaiApiType.AzureOpenAI
    max_retries=20,
)

token_encoder = tiktoken.get_encoding("cl100k_base")

text_embedder = OpenAIEmbedding(
    api_key=api_key,
    api_base=None,
    api_type=OpenaiApiType.OpenAI,
    model=embedding_model,
    deployment_name=embedding_model,
    max_retries=20,
)

In [13]:
context_builder = LocalSearchMixedContext(
    community_reports=reports,
    text_units=text_units,
    entities=entities,
    relationships=relationships,
    # covariates=covariates,
    entity_text_embeddings=description_embedding_store,
    embedding_vectorstore_key=EntityVectorStoreKey.ID,  # if the vectorstore uses entity title as ids, set this to EntityVectorStoreKey.TITLE
    text_embedder=text_embedder,
    token_encoder=token_encoder,
)

### Create local search engine

In [14]:
# text_unit_prop: proportion of context window dedicated to related text units
# community_prop: proportion of context window dedicated to community reports.
# The remaining proportion is dedicated to entities and relationships. Sum of text_unit_prop and community_prop should be <= 1
# conversation_history_max_turns: maximum number of turns to include in the conversation history.
# conversation_history_user_turns_only: if True, only include user queries in the conversation history.
# top_k_mapped_entities: number of related entities to retrieve from the entity description embedding store.
# top_k_relationships: control the number of out-of-network relationships to pull into the context window.
# include_entity_rank: if True, include the entity rank in the entity table in the context window. Default entity rank = node degree.
# include_relationship_weight: if True, include the relationship weight in the context window.
# include_community_rank: if True, include the community rank in the context window.
# return_candidate_context: if True, return a set of dataframes containing all candidate entity/relationship/covariate records that
# could be relevant. Note that not all of these records will be included in the context window. The "in_context" column in these
# dataframes indicates whether the record is included in the context window.
# max_tokens: maximum number of tokens to use for the context window.


local_context_params = {
    "text_unit_prop": 0.5,
    "community_prop": 0.1,
    "conversation_history_max_turns": 5,
    "conversation_history_user_turns_only": True,
    "top_k_mapped_entities": 10,
    "top_k_relationships": 10,
    "include_entity_rank": True,
    "include_relationship_weight": True,
    "include_community_rank": False,
    "return_candidate_context": False,
    "embedding_vectorstore_key": EntityVectorStoreKey.ID,  # set this to EntityVectorStoreKey.TITLE if the vectorstore uses entity title as ids
    "max_tokens": 12_000,  # change this based on the token limit you have on your model (if you are using a model with 8k limit, a good setting could be 5000)
}

llm_params = {
    "max_tokens": 2_000,  # change this based on the token limit you have on your model (if you are using a model with 8k limit, a good setting could be 1000=1500)
    "temperature": 0.0,
}

In [15]:
search_engine = LocalSearch(
    llm=llm,
    context_builder=context_builder,
    token_encoder=token_encoder,
    llm_params=llm_params,
    context_builder_params=local_context_params,
    response_type="multiple paragraph",  # free form text describing the response type and format, can be anything, e.g. prioritized list, single paragraph, multiple paragraphs, multiple-page report
)

### Run local search on sample queries

In [16]:
query = """
What medication should be used to treat a patient who may have combination symptoms of Aerophagy, Catalepsy, and Echolalia?
"""
result = await search_engine.asearch(query)
print(result.response)

## Treatment Options for Combination Symptoms of Aerophagy, Catalepsy, and Echolalia

When considering treatment for a patient exhibiting symptoms of aerophagy, catalepsy, and echolalia, it is essential to recognize that these symptoms can be associated with various neurological and psychiatric conditions, including Gilles De La Tourette Syndrome and Schizophrenia. The choice of medication should be tailored to the specific diagnosis and the individual patient's needs.

### Medications to Consider

1. **Haloperidol**: This antipsychotic medication is commonly used to manage symptoms of Gilles De La Tourette Syndrome and can help alleviate involuntary movements and vocalizations associated with the disorder. It has been noted for its effectiveness in treating tics and other related symptoms [Data: Sources (111); Relationships (1022)].

2. **Pimozide**: Another medication specifically indicated for Gilles De La Tourette Syndrome, pimozide can help reduce the frequency and severity of tics, which may include symptoms like echolalia [Data: Sources (111); Relationships (1019)].

3. **Olanzapine**: This atypical antipsychotic can also be beneficial in managing symptoms associated with Gilles De La Tourette Syndrome and may help with mood stabilization, which can be relevant if the patient exhibits emotional dysregulation alongside their symptoms [Data: Sources (111); Relationships (1020)].

4. **Mecamylamine**: This medication has been noted to palliate symptoms associated with Gilles De La Tourette Syndrome, potentially addressing some of the involuntary aspects of the symptoms [Data: Sources (111); Relationships (1021)].

5. **Perphenazine**: This antipsychotic may also help alleviate symptoms of Gilles De La Tourette Syndrome, making it a potential option for managing the combination of symptoms presented [Data: Sources (111); Relationships (1024)].

### Conclusion

In summary, the treatment of a patient with symptoms of aerophagy, catalepsy, and echolalia may involve a combination of medications such as haloperidol, pimozide, olanzapine, mecamylamine, and perphenazine. It is crucial to conduct a thorough assessment to determine the underlying condition and tailor the treatment plan accordingly. Consulting with a healthcare professional specializing in neurology or psychiatry is recommended to ensure the best outcomes for the patient.

In [17]:
result.context_data

{'reports':    id                                              title  \
 0  73  Gilles De La Tourette Syndrome and Associated ...
 1  73  Gilles De La Tourette Syndrome and Associated ...

                                              content
 0  # Gilles De La Tourette Syndrome and Associate...
 1  # Gilles De La Tourette Syndrome and Associate...  ,
 'relationships':       id                                 source  \
 0   1003                              CATALEPSY
 1   1002                              ECHOLALIA
 2   1006         GILLES DE LA TOURETTE SYNDROME
 3   1022         GILLES DE LA TOURETTE SYNDROME
 4   1019         GILLES DE LA TOURETTE SYNDROME
 5   1020         GILLES DE LA TOURETTE SYNDROME
 6   1021         GILLES DE LA TOURETTE SYNDROME
 7   1024         GILLES DE LA TOURETTE SYNDROME
 8    791                     MULTIPLE SCLEROSIS
 9    790                     MULTIPLE SCLEROSIS
 10   792                     MULTIPLE SCLEROSIS
 11   763                     MULTIPLE SCLEROSIS
 12   730                     MULTIPLE SCLEROSIS
 13  1005                              CATALEPSY
 14   141                             CLONAZEPAM
 15  1724                    PARKINSON'S DISEASE
 16  1721                    PARKINSON'S DISEASE
 17  1275                    ALZHEIMER'S DISEASE
 18  1313                    ALZHEIMER'S DISEASE
 19  1315                    ALZHEIMER'S DISEASE
 20   140                             CLONAZEPAM
 21  2868                           BENZATROPINE
 22  2878                      AUTISTIC DISORDER
 23   956                          SCHIZOPHRENIA
 24   955                          SCHIZOPHRENIA
 25   958                          SCHIZOPHRENIA
 26  1004                              CATALEPSY
 27   139                             CLONAZEPAM
 28  2466                       BIPOLAR DISORDER
 29  2472                       BIPOLAR DISORDER
 30  2864                            HALOPERIDOL
 31  2882                       CONDUCT DISORDER
 32   937  CHRONIC OBSTRUCTIVE PULMONARY DISEASE
 33  2736                        PROSTATE CANCER
 34    27                 RESTLESS LEGS SYNDROME
 35  2654                  ENDOGENOUS DEPRESSION
 36  2192          AMYOTROPHIC LATERAL SCLEROSIS
 37  1591                   SYSTEMIC SCLERODERMA
 38  1759                                 ANOMIA
 39  2835                            GALANTAMINE

                                                target  \
 0                      GILLES DE LA TOURETTE SYNDROME
 1                      GILLES DE LA TOURETTE SYNDROME
 2                                           AEROPHAGY
 3                                         HALOPERIDOL
 4                                            PIMOZIDE
 5                                          OLANZAPINE
 6                                        MECAMYLAMINE
 7                                        PERPHENAZINE
 8                                           CATALEPSY
 9                                           AEROPHAGY
 10                                          ECHOLALIA
 11                                   DEXTROMETHORPHAN
 12  SYMPTOMS OF AGRAPHIA, ANOXIA, ARTICULATION DIS...
 13                                PARKINSON'S DISEASE
 14                                PARKINSON'S DISEASE
 15                                       BENZATROPINE
 16                                          RAMELTEON
 17                                        GALANTAMINE
 18                                       BENZATROPINE
 19                                        HALOPERIDOL
 20                                  AUTISTIC DISORDER
 21                                  AUTISTIC DISORDER
 22                                       ARIPIPRAZOLE
 23                                          CATALEPSY
 24                                          ECHOLALIA
 25                                          AEROPHAGY
 26                                  EPILEPSY SYNDROME
 27                                  EPILEPSY SYNDROME
 28                                       ESCITALOPRAM
 29                                     CHLORPROMAZINE
 30                                   CONDUCT DISORDER
 31                                     CHLORPROMAZINE
 32                                     ACETYLCYSTEINE
 33                                     METOCLOPRAMIDE
 34                                         CLONAZEPAM
 35                                       ESCITALOPRAM
 36                                   DEXTROMETHORPHAN
 37                                         ALPRAZOLAM
 38                                        GALANTAMINE
 39                                        ALZHEIMER'S

                                           description weight rank links  \
 0   Catalepsy is a symptom that can be exhibited b...   13.0   36     8
 1   Echolalia is a symptom commonly observed in in...    9.0   34     8
 2   Gilles De La Tourette Syndrome is a neurologic...   13.0   34     8
 3   Haloperidol is an antipsychotic medication use...    8.0   34     8
 4   Pimozide is a medication used to palliate the ...    8.0   32     8
 5   Olanzapine is a medication that can help allev...    8.0   32     8
 6   Mecamylamine can palliate symptoms associated ...    8.0   32     8
 7   Perphenazine may help alleviate symptoms of Gi...    8.0   32     8
 8   Catalepsy can be a neurological symptom associ...    4.0  101     5
 9   Aerophagy may be reported by patients with Mul...    3.0   99     5
 10  Echolalia may occur in individuals with Multip...    1.0   99     5
 11  Dextromethorphan can palliate symptoms of Mult...    7.0   98     5
 12  Multiple Sclerosis is identified as the diseas...    1.0   97     5
 13  Catalepsy is a symptom associated with Parkins...   16.0   36     4
 14  Clonazepam can palliate the symptoms of Parkin...   18.0   35     4
 15  Benzatropine can palliate the symptoms of Park...   18.0   34     4
 16  Ramelteon can palliate the symptoms of Parkins...   18.0   32     4
 17  Galantamine is a medication that is used in th...   47.0   79     3
 18  Benzatropine can palliate the symptoms of Alzh...   12.0   79     3
 19  Haloperidol can palliate the symptoms of Alzhe...   12.0   79     3
 20  Clonazepam can palliate the symptoms of Autist...   12.0   32     3
 21  Benzatropine can palliate the symptoms of Auti...   12.0   31     3
 22  Aripiprazole can palliate the symptoms of Auti...   12.0   29     3
 23  Catalepsy is recognized as a symptom associate...   15.0   20     3
 24  Echolalia is a symptom that has been identifie...   21.0   18     3
 25  Aerophagy is recognized as a symptom that alig...   14.0   18     3
 26  Catalepsy is a symptom presented by Epilepsy S...    8.0   36     2
 27             Clonazepam can treat Epilepsy Syndrome    9.0   35     2
 28  Escitalopram is a medication that can palliate...    8.0   32     2
 29  Chlorpromazine is a medication that can pallia...    8.0   32     2
 30  Haloperidol can palliate the symptoms of Condu...    2.0   17     2
 31  Chlorpromazine can palliate the symptoms of Co...   18.0   16     2
 32  Acetylcysteine can palliate the symptoms of Ch...    7.0   50     1
 33  Metoclopramide can palliate symptoms of Prosta...    6.0   41     1
 34     Clonazepam can palliate Restless Legs Syndrome   14.0   34     1
 35  Escitalopram can palliate the symptoms of Endo...   18.0   33     1
 36  Dextromethorphan can palliate symptoms of Amyo...   12.0   24     1
 37  Alprazolam can palliate the symptoms of System...    7.0   23     1
 38  Galantamine is a treatment for Alzheimer's Dis...    9.0   12     1
 39  Galantamine is a treatment for Alzheimer's Dis...    9.0    9     1

     in_context
 0         True
 1         True
 2         True
 3         True
 4         True
 5         True
 6         True
 7         True
 8         True
 9         True
 10        True
 11        True
 12        True
 13        True
 14        True
 15        True
 16        True
 17        True
 18        True
 19        True
 20        True
 21        True
 22        True
 23        True
 24        True
 25        True
 26        True
 27        True
 28        True
 29        True
 30        True
 31        True
 32        True
 33        True
 34        True
 35        True
 36        True
 37        True
 38        True
 39        True  ,
 'entities':      id                                             entity  \
 0   715                                       MECAMYLAMINE
 1    88                                          ECHOLALIA
 2    91                                          AEROPHAGY
 3   716                                        HALOPERIDOL
 4    89                                          CATALEPSY
 5   892                                          RAMELTEON
 6   889                                     CHLORPROMAZINE
 7   718                                       PERPHENAZINE
 8   761                                       BENZATROPINE
 9   936                                     ACETYLCYSTEINE
 10  714                                         OLANZAPINE
 11  500                                        GALANTAMINE
 12  824                                     METOCLOPRAMIDE
 13  193  SYMPTOMS OF AGRAPHIA, ANOXIA, ARTICULATION DIS...
 14  455                                         ALPRAZOLAM
 15  408                                       ESCITALOPRAM
 16   28                                         CLONAZEPAM
 17  713                                           PIMOZIDE
 18  272                                   DEXTROMETHORPHAN
 19  837                                       ARIPIPRAZOLE

                                           description number of relationships  \
 0   Mecamylamine is a compound that can palliate s...                       1
 1   Echolalia is a complex symptom characterized b...                       3
 2   Aerophagy is a condition characterized by the ...                       3
 3   Haloperidol is a versatile antipsychotic medic...                       3
 4   CATALEPSY is a neurological condition characte...                       5
 5   Ramelteon is a compound that can palliate the ...                       1
 6   Chlorpromazine is an antipsychotic medication ...                       2
 7   Perphenazine is a medication that may help all...                       1
 8   Benzatropine is a compound known for its abili...                       3
 9   Acetylcysteine is a medication that can help p...                       1
 10  Olanzapine is a medication that can help allev...                       1
 11  Galantamine is a compound and medication prima...                       3
 12  Metoclopramide is a compound that can palliate...                       1
 13  Symptoms including agraphia, anoxia, and artic...                       1
 14  Alprazolam is a compound that can palliate the...                       1
 15  Escitalopram is a medication that is primarily...                       2
 16  Clonazepam is a compound that serves multiple ...                       4
 17  Pimozide is a medication used to palliate the ...                       1
 18  Dextromethorphan is a compound that serves mul...                       2
 19  Aripiprazole is a compound that can palliate t...                       1

     in_context
 0         True
 1         True
 2         True
 3         True
 4         True
 5         True
 6         True
 7         True
 8         True
 9         True
 10        True
 11        True
 12        True
 13        True
 14        True
 15        True
 16        True
 17        True
 18        True
 19        True  ,
 'sources':     id                                               text
 0  111  [Gilles De La Tourette Syndrome] is the name o...
 1    7   Gilles De La Tourette Syndrome. The disease w...
 2    8  olalia is not Gilles De La Tourette Syndrome a...
 3  147   This is incorrect, as Ibuprofen is not a targ...
 4    6   new research, it is found that the symptoms a...
 5  134  [Conduct Disorder] is the name of a kind of di...}

In [18]:
result.context_text

'id|title|content\n73|Gilles De La Tourette Syndrome and Associated Neurological Conditions|"# Gilles De La Tourette Syndrome and Associated Neurological Conditions\n\nThe community focuses on Gilles De La Tourette Syndrome (GTS) and its relationships with various neurological structures and conditions. Key entities include the Internal Capsule of Telencephalon, Cerebellar Nuclear Complex, and various medications used to manage GTS symptoms. The interconnectedness of these entities highlights the complexity of GTS and its implications for treatment and understanding of related disorders.\n\n## Gilles De La Tourette Syndrome as a central entity\n\nGilles De La Tourette Syndrome is a neurological disorder characterized by involuntary tics, making it the focal point of this community. The disorder\'s complexity is underscored by its symptoms, which can vary widely among individuals. GTS not only affects motor functions but also has implications for emotional and cognitive processes, indicating a need for comprehensive management strategies. The relationships with other neurological conditions and structures further emphasize the importance of understanding GTS in a broader context. [Data: Entities (90), Relationships (71, 116, 103)]\n\n## Role of the Internal Capsule of Telencephalon\n\nThe Internal Capsule of Telencephalon is crucial in understanding the neural pathways associated with Gilles De La Tourette Syndrome. It is implicated in both GTS and Bipolar Disorder, suggesting a shared neural basis for mood regulation and motor control. This relationship highlights the importance of the Internal Capsule in the management of GTS, as it may influence treatment approaches and outcomes. Understanding its role can lead to better-targeted therapies for individuals affected by GTS. [Data: Entities (709), Relationships (2478, 1015)]\n\n## Cerebellar Nuclear Complex\'s involvement in GTS\n\nThe Cerebellar Nuclear Complex is another significant structure related to Gilles De La Tourette Syndrome. Its involvement suggests that motor control and coordination may be affected in individuals with GTS. This relationship indicates that treatments targeting the cerebellum could potentially alleviate some symptoms of GTS, emphasizing the need for a multidisciplinary approach in managing the disorder. [Data: Entities (711), Relationships (1017)]\n\n## Medications used to manage GTS symptoms\n\nSeveral medications, including Pimozide, Olanzapine, and Haloperidol, are used to manage symptoms of Gilles De La Tourette Syndrome. These medications target various neurotransmitter systems, indicating the complexity of pharmacological management in GTS. The choice of medication can significantly impact the quality of life for individuals with GTS, highlighting the importance of personalized treatment plans. Understanding the efficacy and side effects of these medications is crucial for optimizing patient care. [Data: Entities (713, 714, 1022, 1023, 1020)]\n\n## Symptoms associated with Gilles De La Tourette Syndrome\n\nGilles De La Tourette Syndrome is associated with a range of symptoms, including dyskinesia, language disorders, and hyperkinesis. These symptoms can complicate the diagnosis and treatment of GTS, as they may overlap with other neurological conditions. Recognizing the full spectrum of symptoms is essential for accurate diagnosis and effective management, as it can influence treatment decisions and patient outcomes. [Data: Entities (722, 707, 1014, 1013, 1010)]"\n\n\nid|title|content\n73|Gilles De La Tourette Syndrome and Associated Neurological Conditions|"# Gilles De La Tourette Syndrome and Associated Neurological Conditions\n\nThe community focuses on Gilles De La Tourette Syndrome (GTS) and its relationships with various neurological structures and conditions. Key entities include the Internal Capsule of Telencephalon, Cerebellar Nuclear Complex, and various medications used to manage GTS symptoms. The interconnectedness of these entities highlights the complexity of GTS and its implications for treatment and understanding of related disorders.\n\n## Gilles De La Tourette Syndrome as a central entity\n\nGilles De La Tourette Syndrome is a neurological disorder characterized by involuntary tics, making it the focal point of this community. The disorder\'s complexity is underscored by its symptoms, which can vary widely among individuals. GTS not only affects motor functions but also has implications for emotional and cognitive processes, indicating a need for comprehensive management strategies. The relationships with other neurological conditions and structures further emphasize the importance of understanding GTS in a broader context. [Data: Entities (90), Relationships (71, 116, 103)]\n\n## Role of the Internal Capsule of Telencephalon\n\nThe Internal Capsule of Telencephalon is crucial in understanding the neural pathways associated with Gilles De La Tourette Syndrome. It is implicated in both GTS and Bipolar Disorder, suggesting a shared neural basis for mood regulation and motor control. This relationship highlights the importance of the Internal Capsule in the management of GTS, as it may influence treatment approaches and outcomes. Understanding its role can lead to better-targeted therapies for individuals affected by GTS. [Data: Entities (709), Relationships (2478, 1015)]\n\n## Cerebellar Nuclear Complex\'s involvement in GTS\n\nThe Cerebellar Nuclear Complex is another significant structure related to Gilles De La Tourette Syndrome. Its involvement suggests that motor control and coordination may be affected in individuals with GTS. This relationship indicates that treatments targeting the cerebellum could potentially alleviate some symptoms of GTS, emphasizing the need for a multidisciplinary approach in managing the disorder. [Data: Entities (711), Relationships (1017)]\n\n## Medications used to manage GTS symptoms\n\nSeveral medications, including Pimozide, Olanzapine, and Haloperidol, are used to manage symptoms of Gilles De La Tourette Syndrome. These medications target various neurotransmitter systems, indicating the complexity of pharmacological management in GTS. The choice of medication can significantly impact the quality of life for individuals with GTS, highlighting the importance of personalized treatment plans. Understanding the efficacy and side effects of these medications is crucial for optimizing patient care. [Data: Entities (713, 714, 1022, 1023, 1020)]\n\n## Symptoms associated with Gilles De La Tourette Syndrome\n\nGilles De La Tourette Syndrome is associated with a range of symptoms, including dyskinesia, language disorders, and hyperkinesis. These symptoms can complicate the diagnosis and treatment of GTS, as they may overlap with other neurological conditions. Recognizing the full spectrum of symptoms is essential for accurate diagnosis and effective management, as it can influence treatment decisions and patient outcomes. [Data: Entities (722, 707, 1014, 1013, 1010)]"\n\n\n-----Entities-----\nid|entity|description|number of relationships\n715|MECAMYLAMINE|Mecamylamine is a compound that can palliate symptoms associated with Gilles De La Tourette Syndrome.|1\n88|ECHOLALIA|Echolalia is a complex symptom characterized by the involuntary or automatic repetition of words, phrases, or vocalizations made by another person. It is notably associated with several psychological and developmental conditions. In the context of Gilles De La Tourette Syndrome, echolalia manifests as an involuntary repetition of speech, while in individuals with schizophrenia, it plays a significant role in the clinical presentation of the disorder. Additionally, echolalia is commonly observed in individuals with autism and other developmental disorders, where it involves the unsolicited repetition of phrases or noises heard from others. Overall, echolalia serves as an important indicator in various psychological and developmental contexts, highlighting its relevance in understanding and diagnosing these conditions.|3\n91|AEROPHAGY|Aerophagy is a condition characterized by the excessive swallowing of air, which can lead to symptoms such as bloating and discomfort. This condition is notably associated with Gilles De La Tourette Syndrome, where it manifests as a symptom. Overall, aerophagy involves the involuntary intake of air, resulting in various gastrointestinal issues.|3\n716|HALOPERIDOL|Haloperidol is a versatile antipsychotic medication that is utilized in the treatment of various conditions. It is known to palliate the symptoms of Alzheimer\'s Disease, providing relief to patients experiencing cognitive decline. Additionally, Haloperidol is effective in managing symptoms associated with Conduct Disorder, aiding in the treatment of this behavioral condition. Furthermore, it is also used to address symptoms of Gilles De La Tourette Syndrome, helping to alleviate the involuntary movements and vocalizations characteristic of this disorder. Overall, Haloperidol serves as an important therapeutic option for multiple psychiatric and neurological conditions.|3\n89|CATALEPSY|CATALEPSY is a neurological condition characterized by a trance-like state or seizure, which involves a loss of sensation and consciousness, accompanied by rigidity of the body. This condition often results in a lack of response to external stimuli and is associated with various neurological disorders. Catalepsy can manifest as a symptom in several conditions, including Epilepsy Syndrome, Gilles De La Tourette Syndrome, Parkinson\'s Disease, and Schizophrenia, reflecting the complex symptomatology of these disorders.|5\n892|RAMELTEON|Ramelteon is a compound that can palliate the symptoms of Parkinson\'s Disease.|1\n889|CHLORPROMAZINE|Chlorpromazine is an antipsychotic medication that is utilized in the treatment of various mental health conditions. It is known to palliate the symptoms of Conduct Disorder and is also effective in managing symptoms associated with Bipolar Disorder. This compound serves as a versatile option in psychiatric care, addressing a range of behavioral and mood-related symptoms.|2\n718|PERPHENAZINE|Perphenazine is a medication that may help alleviate symptoms of Gilles De La Tourette Syndrome.|1\n761|BENZATROPINE|Benzatropine is a compound known for its ability to palliate the symptoms associated with several neurological conditions. Specifically, it has been found to alleviate symptoms of Alzheimer\'s Disease, Autistic Disorder, and Parkinson\'s Disease. This multifaceted therapeutic potential makes Benzatropine a significant compound in the management of these disorders.|3\n936|ACETYLCYSTEINE|Acetylcysteine is a medication that can help palliate the symptoms of Chronic Obstructive Pulmonary Disease.|1\n714|OLANZAPINE|Olanzapine is a medication that can help alleviate symptoms of Gilles De La Tourette Syndrome.|1\n500|GALANTAMINE|Galantamine is a compound and medication primarily used in the treatment of Alzheimer\'s Disease. It is prescribed to aid in alleviating memory loss and cognitive issues associated with this condition. Galantamine helps improve memory and cognitive function, making it a valuable option for individuals suffering from Alzheimer\'s. It is important to note that Galantamine is not typically used for the treatment of Parkinson\'s Disease. Overall, Galantamine is recognized as an effective treatment specifically for Alzheimer\'s Disease.|3\n824|METOCLOPRAMIDE|Metoclopramide is a compound that can palliate symptoms of Prostate Cancer, often used to treat nausea.|1\n193|SYMPTOMS OF AGRAPHIA, ANOXIA, ARTICULATION DISORDERS|Symptoms including agraphia, anoxia, and articulation disorders are now primarily associated with Multiple Sclerosis rather than Amyotrophic Lateral Sclerosis.|1\n455|ALPRAZOLAM|Alprazolam is a compound that can palliate the symptoms of Systemic Scleroderma.|1\n408|ESCITALOPRAM|Escitalopram is a medication that is primarily used to treat depression and anxiety. It is effective in alleviating the symptoms of Endogenous Depression and can also provide relief for symptoms associated with Bipolar Disorder. This compound plays a significant role in managing mood disorders, making it a valuable option in psychiatric treatment.|2\n28|CLONAZEPAM|Clonazepam is a compound that serves multiple therapeutic purposes. It is utilized to palliate the symptoms of Autistic Disorder and Parkinson\'s Disease, indicating its potential in managing various neurological conditions. Additionally, Clonazepam is employed in the treatment of Epilepsy Syndrome, highlighting its role in seizure management. Furthermore, this medication is commonly used to treat anxiety and seizure disorders, and it may also help alleviate symptoms associated with Restless Legs Syndrome. Overall, Clonazepam is recognized for its diverse applications in addressing both psychiatric and neurological symptoms.|4\n713|PIMOZIDE|Pimozide is a medication used to palliate the symptoms of Gilles De La Tourette Syndrome.|1\n272|DEXTROMETHORPHAN|Dextromethorphan is a compound that serves multiple therapeutic purposes. It is primarily known as a medication used to relieve coughs. Additionally, it has been noted for its potential to palliate symptoms associated with neurological conditions, specifically Multiple Sclerosis and Amyotrophic Lateral Sclerosis. This dual role highlights Dextromethorphan\'s versatility in providing symptomatic relief for patients suffering from these serious health conditions.|2\n837|ARIPIPRAZOLE|Aripiprazole is a compound that can palliate the symptoms of Autistic Disorder.|1\n\n\n-----Relationships-----\nid|source|target|description|weight|rank|links\n1003|CATALEPSY|GILLES DE LA TOURETTE SYNDROME|Catalepsy is a symptom that can be exhibited by individuals diagnosed with Gilles De La Tourette Syndrome. Historically, catalepsy was regarded as a potential symptom associated with Gilles De La Tourette Syndrome, indicating a connection between the two conditions.|13.0|36|8\n1002|ECHOLALIA|GILLES DE LA TOURETTE SYNDROME|Echolalia is a symptom commonly observed in individuals with Gilles De La Tourette Syndrome. It has been noted as a characteristic feature associated with this neurological disorder, indicating that echolalia may manifest in those affected by Gilles De La Tourette Syndrome.|9.0|34|8\n1006|GILLES DE LA TOURETTE SYNDROME|AEROPHAGY|Gilles De La Tourette Syndrome is a neurological disorder characterized by repetitive, involuntary movements and vocalizations known as tics. One of the symptoms that can be presented by individuals with Gilles De La Tourette Syndrome is aerophagy, which refers to the excessive swallowing of air. This symptom has been previously associated with the syndrome, indicating a potential link between the two conditions.|13.0|34|8\n1022|GILLES DE LA TOURETTE SYNDROME|HALOPERIDOL|Haloperidol is an antipsychotic medication used to treat symptoms of Gilles De La Tourette Syndrome|8.0|34|8\n1019|GILLES DE LA TOURETTE SYNDROME|PIMOZIDE|Pimozide is a medication used to palliate the symptoms of Gilles De La Tourette Syndrome|8.0|32|8\n1020|GILLES DE LA TOURETTE SYNDROME|OLANZAPINE|Olanzapine is a medication that can help alleviate symptoms of Gilles De La Tourette Syndrome|8.0|32|8\n1021|GILLES DE LA TOURETTE SYNDROME|MECAMYLAMINE|Mecamylamine can palliate symptoms associated with Gilles De La Tourette Syndrome|8.0|32|8\n1024|GILLES DE LA TOURETTE SYNDROME|PERPHENAZINE|Perphenazine may help alleviate symptoms of Gilles De La Tourette Syndrome|8.0|32|8\n791|MULTIPLE SCLEROSIS|CATALEPSY|Catalepsy can be a neurological symptom associated with Multiple Sclerosis.|4.0|101|5\n790|MULTIPLE SCLEROSIS|AEROPHAGY|Aerophagy may be reported by patients with Multiple Sclerosis due to gastrointestinal symptoms.|3.0|99|5\n792|MULTIPLE SCLEROSIS|ECHOLALIA|Echolalia may occur in individuals with Multiple Sclerosis due to neurological involvement affecting communication.|1.0|99|5\n763|MULTIPLE SCLEROSIS|DEXTROMETHORPHAN|Dextromethorphan can palliate symptoms of Multiple Sclerosis|7.0|98|5\n730|MULTIPLE SCLEROSIS|SYMPTOMS OF AGRAPHIA, ANOXIA, ARTICULATION DISORDERS|Multiple Sclerosis is identified as the disease causing symptoms of agraphia, anoxia, and articulation disorders|1.0|97|5\n1005|CATALEPSY|PARKINSON\'S DISEASE|Catalepsy is a symptom associated with Parkinson\'s Disease|16.0|36|4\n141|CLONAZEPAM|PARKINSON\'S DISEASE|Clonazepam can palliate the symptoms of Parkinson\'s Disease|18.0|35|4\n1724|PARKINSON\'S DISEASE|BENZATROPINE|Benzatropine can palliate the symptoms of Parkinson\'s Disease|18.0|34|4\n1721|PARKINSON\'S DISEASE|RAMELTEON|Ramelteon can palliate the symptoms of Parkinson\'s Disease|18.0|32|4\n1275|ALZHEIMER\'S DISEASE|GALANTAMINE|Galantamine is a medication that is used in the treatment of Alzheimer\'s Disease. It is effective in alleviating symptoms associated with the condition, particularly in improving memory. The prescription of Galantamine for Alzheimer\'s Disease indicates a direct relationship between the two, highlighting its role as a therapeutic option for individuals affected by this neurodegenerative disorder. Overall, Galantamine serves as a valuable treatment to help manage the symptoms of Alzheimer\'s Disease.|47.0|79|3\n1313|ALZHEIMER\'S DISEASE|BENZATROPINE|Benzatropine can palliate the symptoms of Alzheimer\'s Disease|12.0|79|3\n1315|ALZHEIMER\'S DISEASE|HALOPERIDOL|Haloperidol can palliate the symptoms of Alzheimer\'s Disease|12.0|79|3\n140|CLONAZEPAM|AUTISTIC DISORDER|Clonazepam can palliate the symptoms of Autistic Disorder|12.0|32|3\n2868|BENZATROPINE|AUTISTIC DISORDER|Benzatropine can palliate the symptoms of Autistic Disorder|12.0|31|3\n2878|AUTISTIC DISORDER|ARIPIPRAZOLE|Aripiprazole can palliate the symptoms of Autistic Disorder|12.0|29|3\n956|SCHIZOPHRENIA|CATALEPSY|Catalepsy is recognized as a symptom associated with Schizophrenia, indicating a significant relationship between the two. It has been identified as part of the clinical presentation of Schizophrenia, suggesting that individuals diagnosed with this mental disorder may exhibit cataleptic symptoms. Overall, the connection between Catalepsy and Schizophrenia highlights the complexity of the symptoms that can manifest in those affected by this condition.|15.0|20|3\n955|SCHIZOPHRENIA|ECHOLALIA|Echolalia is a symptom that has been identified as part of the clinical presentation of schizophrenia. It is described as a symptom that is more frequently observed in individuals with schizophrenia, indicating a significant relationship between the two. This association highlights the relevance of echolalia in understanding the manifestations of schizophrenia.|21.0|18|3\n958|SCHIZOPHRENIA|AEROPHAGY|Aerophagy is recognized as a symptom that aligns closely with Schizophrenia. This association indicates a relationship between the two, suggesting that individuals with Schizophrenia may experience aerophagy as part of their symptomatology.|14.0|18|3\n1004|CATALEPSY|EPILEPSY SYNDROME|Catalepsy is a symptom presented by Epilepsy Syndrome|8.0|36|2\n139|CLONAZEPAM|EPILEPSY SYNDROME|Clonazepam can treat Epilepsy Syndrome|9.0|35|2\n2466|BIPOLAR DISORDER|ESCITALOPRAM|Escitalopram is a medication that can palliate symptoms of Bipolar Disorder|8.0|32|2\n2472|BIPOLAR DISORDER|CHLORPROMAZINE|Chlorpromazine is a medication that can palliate symptoms of Bipolar Disorder|8.0|32|2\n2864|HALOPERIDOL|CONDUCT DISORDER|Haloperidol can palliate the symptoms of Conduct Disorder|2.0|17|2\n2882|CONDUCT DISORDER|CHLORPROMAZINE|Chlorpromazine can palliate the symptoms of Conduct Disorder|18.0|16|2\n937|CHRONIC OBSTRUCTIVE PULMONARY DISEASE|ACETYLCYSTEINE|Acetylcysteine can palliate the symptoms of Chronic Obstructive Pulmonary Disease|7.0|50|1\n2736|PROSTATE CANCER|METOCLOPRAMIDE|Metoclopramide can palliate symptoms of Prostate Cancer|6.0|41|1\n27|RESTLESS LEGS SYNDROME|CLONAZEPAM|Clonazepam can palliate Restless Legs Syndrome|14.0|34|1\n2654|ENDOGENOUS DEPRESSI

#### Inspecting the context data used to generate the response

In [19]:
a = result.context_data["entities"]

In [20]:
a

,id,entity,description,number of relationships,in_context
0,715,MECAMYLAMINE,Mecamylamine is a compound that can palliate s...,1,True
1,88,ECHOLALIA,Echolalia is a complex symptom characterized b...,3,True
2,91,AEROPHAGY,Aerophagy is a condition characterized by the ...,3,True
3,716,HALOPERIDOL,Haloperidol is a versatile antipsychotic medic...,3,True
4,89,CATALEPSY,CATALEPSY is a neurological condition characte...,5,True
5,892,RAMELTEON,Ramelteon is a compound that can palliate the ...,1,True
6,889,CHLORPROMAZINE,Chlorpromazine is an antipsychotic medication ...,2,True
7,718,PERPHENAZINE,Perphenazine is a medication that may help all...,1,True
8,761,BENZATROPINE,Benzatropine is a compound known for its abili...,3,True
9,936,ACETYLCYSTEINE,Acetylcysteine is a medication that can help p...,1,True
10,714,OLANZAPINE,Olanzapine is a medication that can help allev...,1,True
11,500,GALANTAMINE,Galantamine is a compound and medication prima...,3,True
12,824,METOCLOPRAMIDE,Metoclopramide is a compound that can palliate...,1,True
13,193,"SYMPTOMS OF AGRAPHIA, ANOXIA, ARTICULATION DIS...","Symptoms including agraphia, anoxia, and artic...",1,True
14,455,ALPRAZOLAM,Alprazolam is a compound that can palliate the...,1,True
15,408,ESCITALOPRAM,Escitalopram is a medication that is primarily...,2,True
16,28,CLONAZEPAM,Clonazepam is a compound that serves multiple ...,4,True
17,713,PIMOZIDE,Pimozide is a medication used to palliate the ...,1,True
18,272,DEXTROMETHORPHAN,Dextromethorphan is a compound that serves mul...,2,True
19,837,ARIPIPRAZOLE,Aripiprazole is a compound that can palliate t...,1,True

In [21]:
df3 = result.context_data["relationships"]

In [22]:
df3

,id,source,target,description,weight,rank,links,in_context
0,1003,CATALEPSY,GILLES DE LA TOURETTE SYNDROME,Catalepsy is a symptom that can be exhibited b...,13.0,36,8,True
1,1002,ECHOLALIA,GILLES DE LA TOURETTE SYNDROME,Echolalia is a symptom commonly observed in in...,9.0,34,8,True
2,1006,GILLES DE LA TOURETTE SYNDROME,AEROPHAGY,Gilles De La Tourette Syndrome is a neurologic...,13.0,34,8,True
3,1022,GILLES DE LA TOURETTE SYNDROME,HALOPERIDOL,Haloperidol is an antipsychotic medication use...,8.0,34,8,True
4,1019,GILLES DE LA TOURETTE SYNDROME,PIMOZIDE,Pimozide is a medication used to palliate the ...,8.0,32,8,True
5,1020,GILLES DE LA TOURETTE SYNDROME,OLANZAPINE,Olanzapine is a medication that can help allev...,8.0,32,8,True
6,1021,GILLES DE LA TOURETTE SYNDROME,MECAMYLAMINE,Mecamylamine can palliate symptoms associated ...,8.0,32,8,True
7,1024,GILLES DE LA TOURETTE SYNDROME,PERPHENAZINE,Perphenazine may help alleviate symptoms of Gi...,8.0,32,8,True
8,791,MULTIPLE SCLEROSIS,CATALEPSY,Catalepsy can be a neurological symptom associ...,4.0,101,5,True
9,790,MULTIPLE SCLEROSIS,AEROPHAGY,Aerophagy may be reported by patients with Mul...,3.0,99,5,True
10,792,MULTIPLE SCLEROSIS,ECHOLALIA,Echolalia may occur in individuals with Multip...,1.0,99,5,True
11,763,MULTIPLE SCLEROSIS,DEXTROMETHORPHAN,Dextromethorphan can palliate symptoms of Mult...,7.0,98,5,True
12,730,MULTIPLE SCLEROSIS,"SYMPTOMS OF AGRAPHIA, ANOXIA, ARTICULATION DIS...",Multiple Sclerosis is identified as the diseas...,1.0,97,5,True
13,1005,CATALEPSY,PARKINSON'S DISEASE,Catalepsy is a symptom associated with Parkins...,16.0,36,4,True
14,141,CLONAZEPAM,PARKINSON'S DISEASE,Clonazepam can palliate the symptoms of Parkin...,18.0,35,4,True
15,1724,PARKINSON'S DISEASE,BENZATROPINE,Benzatropine can palliate the symptoms of Park...,18.0,34,4,True
16,1721,PARKINSON'S DISEASE,RAMELTEON,Ramelteon can palliate the symptoms of Parkins...,18.0,32,4,True
17,1275,ALZHEIMER'S DISEASE,GALANTAMINE,Galantamine is a medication that is used in th...,47.0,79,3,True
18,1313,ALZHEIMER'S DISEASE,BENZATROPINE,Benzatropine can palliate the symptoms of Alzh...,12.0,79,3,True
19,1315,ALZHEIMER'S DISEASE,HALOPERIDOL,Haloperidol can palliate the symptoms of Alzhe...,12.0,79,3,True
20,140,CLONAZEPAM,AUTISTIC DISORDER,Clonazepam can palliate the symptoms of Autist...,12.0,32,3,True
21,2868,BENZATROPINE,AUTISTIC DISORDER,Benzatropine can palliate the symptoms of Auti...,12.0,31,3,True
22,2878,AUTISTIC DISORDER,ARIPIPRAZOLE,Aripiprazole can palliate the symptoms of Auti...,12.0,29,3,True
23,956,SCHIZOPHRENIA,CATALEPSY,Catalepsy is recognized as a symptom associate...,15.0,20,3,True
24,955,SCHIZOPHRENIA,ECHOLALIA,Echolalia is a symptom that has been identifie...,21.0,18,3,True
25,958,SCHIZOPHRENIA,AEROPHAGY,Aerophagy is recognized as a symptom that alig...,14.0,18,3,True
26,1004,CATALEPSY,EPILEPSY SYNDROME,Catalepsy is a symptom presented by Epilepsy S...,8.0,36,2,True
27,139,CLONAZEPAM,EPILEPSY SYNDROME,Clonazepam can treat Epilepsy Syndrome,9.0,35,2,True
28,2466,BIPOLAR DISORDER,ESCITALOPRAM,Escitalopram is a medication that can palliate...,8.0,32,2,True
29,2472,BIPOLAR DISORDER,CHLORPROMAZINE,Chlorpromazine is a medication that can pallia...,8.0,32,2,True
30,2864,HALOPERIDOL,CONDUCT DISORDER,Haloperidol can palliate the symptoms of Condu...,2.0,17,2,True
31,2882,CONDUCT DISORDER,CHLORPROMAZINE,Chlorpromazine can palliate the symptoms of Co...,18.0,16,2,True
32,937,CHRONIC OBSTRUCTIVE PULMONARY DISEASE,ACETYLCYSTEINE,Acetylcysteine can palliate the symptoms of Ch...,7.0,50,1,True
33,2736,PROSTATE CANCER,METOCLOPRAMIDE,Metoclopramide can palliate symptoms of Prosta...,6.0,41,1,True
34,27,RESTLESS LEGS SYNDROME,CLONAZEPAM,Clonazepam can palliate Restless Legs Syndrome,14.0,34,1,True
35,2654,ENDOGENOUS DEPRESSION,ESCITALOPRAM,Escitalopram can palliate the symptoms of Endo...,18.0,33,1,True
36,2192,AMYOTROPHIC LATERAL SCLEROSIS,DEXTROMETHORPHAN,Dextromethorphan can palliate symptoms of Amyo...,12.0,24,1,True
37,1591,SYSTEMIC SCLERODERMA,ALPRAZOLAM,Alprazolam can palliate the symptoms of System...,7.0,23,1,True
38,1759,ANOMIA,GALANTAMINE,Galantamine is a treatment for Alzheimer's Dis...,9.0,12,1,True
39,2835,GALANTAMINE,ALZHEIMER'S,Galantamine is a treatment for Alzheimer's Dis...,9.0,9,1,True

In [23]:
tokyo_university_df = df3[
    (df3["source"].isin(["TOKYO UNIVERSITY", "TOKYO"])) | 
    (df3["target"].isin(["TOKYO UNIVERSITY", "TOKYO"]))
]
tokyo_university_df

Empty DataFrame
Columns: [id, source, target, description, weight, rank, links, in_context]
Index: []

In [24]:
result.context_data["reports"]

,id,title,content
0,73,Gilles De La Tourette Syndrome and Associated ...,# Gilles De La Tourette Syndrome and Associate...
1,73,Gilles De La Tourette Syndrome and Associated ...,# Gilles De La Tourette Syndrome and Associate...

In [25]:
result.context_data["sources"]

    id                                               text
0  111  [Gilles De La Tourette Syndrome] is the name o...
1    7   Gilles De La Tourette Syndrome. The disease w...
2    8  olalia is not Gilles De La Tourette Syndrome a...
3  147   This is incorrect, as Ibuprofen is not a targ...
4    6   new research, it is found that the symptoms a...
5  134  [Conduct Disorder] is the name of a kind of di...

In [26]:
# if "claims" in result.context_data:
#     print(result.context_data["claims"].head())

### Question Generation

This function takes a list of user queries and generates the next candidate questions.

In [27]:
# question_generator = LocalQuestionGen(
#     llm=llm,
#     context_builder=context_builder,
#     token_encoder=token_encoder,
#     llm_params=llm_params,
#     context_builder_params=local_context_params,
# )
# question_history = [
#     "Tell me about Agent Mercer",
#     "What happens in Dulce military base?",
# ]
# candidate_questions = await question_generator.agenerate(
#     question_history=question_history, context_data=None, question_count=5
# )
# print(candidate_questions.response)

In [28]:
import networkx as nx
from pyvis.network import Network
import random

# Load the GraphML file
G = nx.read_graphml('/data/yuhui/6/graphrag/alltest/location_dataset/dataset_4_revised/output/20241012-123311/artifacts/merged_graph.graphml')
# Create a Pyvis network
net = Network(notebook=True)

# Convert NetworkX graph to Pyvis network
net.from_nx(G)

# Add colors to nodes
for node in net.nodes:
    node['color'] = "#{:06x}".format(random.randint(0, 0xFFFFFF))

# Save and display the network
net.show('knowledge_graph.html')

ModuleNotFoundError: No module named 'pyvis'