In [11]:
import os

import pandas as pd
import tiktoken

from graphrag.query.context_builder.entity_extraction import EntityVectorStoreKey
from graphrag.query.indexer_adapters import (
    read_indexer_covariates,
    read_indexer_entities,
    read_indexer_relationships,
    read_indexer_reports,
    read_indexer_text_units,
)
from graphrag.query.input.loaders.dfs import (
    store_entity_semantic_embeddings,
)
from graphrag.query.llm.oai.chat_openai import ChatOpenAI
from graphrag.query.llm.oai.embedding import OpenAIEmbedding
from graphrag.query.llm.oai.typing import OpenaiApiType
from graphrag.query.question_gen.local_gen import LocalQuestionGen
from graphrag.query.structured_search.local_search.mixed_context import (
    LocalSearchMixedContext,
)
from graphrag.query.structured_search.local_search.search import LocalSearch
from graphrag.vector_stores.lancedb import LanceDBVectorStore

## Local Search Example

Local search method generates answers by combining relevant data from the AI-extracted knowledge-graph with text chunks of the raw documents. This method is suitable for questions that require an understanding of specific entities mentioned in the documents (e.g. What are the healing properties of chamomile?).

### Load text units and graph data tables as context for local search

- In this test we first load indexing outputs from parquet files to dataframes, then convert these dataframes into collections of data objects aligning with the knowledge model.

### Load tables to dataframes

In [ ]:
# 步骤 1：找到排序最大的文件夹
output_path = "/home/ljc/data/graphrag/alltest/new_corpus_1207/medi_v3_1207_tobeuse_only1/output/"
folders = [os.path.join(output_path, d) for d in os.listdir(output_path) if os.path.isdir(os.path.join(output_path, d))]
latest_folder = max(folders, key=os.path.getmtime)

In [13]:
INPUT_DIR = latest_folder + "/artifacts"
LANCEDB_URI = f"{INPUT_DIR}/lancedb"

COMMUNITY_REPORT_TABLE = "create_final_community_reports"
ENTITY_TABLE = "create_final_nodes"
ENTITY_EMBEDDING_TABLE = "create_final_entities"
RELATIONSHIP_TABLE = "create_final_relationships"
COVARIATE_TABLE = "create_final_covariates"
TEXT_UNIT_TABLE = "create_final_text_units"
COMMUNITY_LEVEL = 2

#### Read entities

In [14]:
# read nodes table to get community and degree data
entity_df = pd.read_parquet(f"{INPUT_DIR}/{ENTITY_TABLE}.parquet")
entity_embedding_df = pd.read_parquet(f"{INPUT_DIR}/{ENTITY_EMBEDDING_TABLE}.parquet")

entities = read_indexer_entities(entity_df, entity_embedding_df, COMMUNITY_LEVEL)

# load description embeddings to an in-memory lancedb vectorstore
# to connect to a remote db, specify url and port values.
description_embedding_store = LanceDBVectorStore(
    collection_name="entity_description_embeddings",
)
description_embedding_store.connect(db_uri=LANCEDB_URI)
entity_description_embeddings = store_entity_semantic_embeddings(
    entities=entities, vectorstore=description_embedding_store
)

print(f"Entity count: {len(entity_df)}")
entity_df.head()

Entity count: 9695

,level,title,type,description,source_id,community,degree,human_readable_id,id,size,graph_embedding,entity_type,top_level_node_id,x,y
0,0,BOOT OR LOGON INITIALIZATION SCRIPTS,EVENT,Boot or Logon Initialization Scripts are techn...,"9c8a7d852d29cf59938b333d040a4d43,dbd1e3609f340...",8,3,0,b45241d70f0e43fca764df95b2b81f77,3.0,"[-0.02192499116063118, -0.0037622004747390747,...",None,b45241d70f0e43fca764df95b2b81f77,4.390680,-5.374512
1,0,RC SCRIPTS,EVENT,RC SCRIPTS refers to an attack technique that ...,"a74287a0a54e50ec9c1b6813cba5ae05,dbd1e3609f340...",8,4,1,4119fd06010c494caa07f439b333f4c5,4.0,"[-0.04574325308203697, -0.024620570242404938, ...",None,4119fd06010c494caa07f439b333f4c5,4.370068,-4.909294
2,0,LOGON SCRIPT (WINDOWS),EVENT,Logon Script (Windows) is an attack technique ...,dbd1e3609f3402a12e0250b46a68b539,8,3,2,d3835bf3dda84ead99deadbeac5d0d7d,3.0,"[-0.04805801808834076, 0.007536540273576975, -...",None,d3835bf3dda84ead99deadbeac5d0d7d,4.379420,-5.583469
3,0,NETWORK LOGON SCRIPT,EVENT,"The ""NETWORK LOGON SCRIPT"" refers to an attack...","1722dbbff4228bec3d11412e53f3e004,dbd1e3609f340...",8,4,3,077d2820ae1845bcbb1803379a3d1eae,4.0,"[-0.08732595294713974, 0.014648603275418282, -...",None,077d2820ae1845bcbb1803379a3d1eae,4.126524,-5.353427
4,0,STARTUP ITEMS,EVENT,Startup Items is an attack technique that invo...,"074f2bde56857c7f8ef4d061ba5f5126,dbd1e3609f340...",8,3,4,3671ea0dd4e84c1a9b02c5ab2c8f4bac,3.0,"[-0.056497808545827866, -0.06328770518302917, ...",None,3671ea0dd4e84c1a9b02c5ab2c8f4bac,4.814841,-6.962210

In [15]:
entity_embedding_df

,id,name,type,description,human_readable_id,graph_embedding,text_unit_ids,description_embedding
0,b45241d70f0e43fca764df95b2b81f77,BOOT OR LOGON INITIALIZATION SCRIPTS,EVENT,Boot or Logon Initialization Scripts are techn...,0,"[-0.02192499116063118, -0.0037622004747390747,...","[9c8a7d852d29cf59938b333d040a4d43, dbd1e3609f3...","[0.007103013340383768, 0.06904760003089905, 0...."
1,4119fd06010c494caa07f439b333f4c5,RC SCRIPTS,EVENT,RC SCRIPTS refers to an attack technique that ...,1,"[-0.04574325308203697, -0.024620570242404938, ...","[a74287a0a54e50ec9c1b6813cba5ae05, dbd1e3609f3...","[0.013611752539873123, 0.051572006195783615, 0..."
2,d3835bf3dda84ead99deadbeac5d0d7d,LOGON SCRIPT (WINDOWS),EVENT,Logon Script (Windows) is an attack technique ...,2,"[-0.04805801808834076, 0.007536540273576975, -...",[dbd1e3609f3402a12e0250b46a68b539],"[-0.008104234002530575, 0.0914725661277771, 0...."
3,077d2820ae1845bcbb1803379a3d1eae,NETWORK LOGON SCRIPT,EVENT,"The ""NETWORK LOGON SCRIPT"" refers to an attack...",3,"[-0.08732595294713974, 0.014648603275418282, -...","[1722dbbff4228bec3d11412e53f3e004, dbd1e3609f3...","[0.0042883530259132385, 0.07738594710826874, 0..."
4,3671ea0dd4e84c1a9b02c5ab2c8f4bac,STARTUP ITEMS,EVENT,Startup Items is an attack technique that invo...,4,"[-0.056497808545827866, -0.06328770518302917, ...","[074f2bde56857c7f8ef4d061ba5f5126, dbd1e3609f3...","[-0.0012583391508087516, 0.06270014494657516, ..."
...,...,...,...,...,...,...,...,...
237,dc1bb549036045d1b46c02e05deeeb40,SESSION COOKIE THEFT,EVENT,Session Cookie Theft is a cyber attack techniq...,1934,"[-0.06690459698438644, -0.043666690587997437, ...",[e29313382dfca90bfc20bdcf13522720],"[0.013443300500512123, -0.037628062069416046, ..."
238,70890fae70dc43e59b7f33f364a25171,LATEST DATA,ORGANIZATION,The latest data refers to recent research find...,1935,"[-0.0046128216199576855, 0.020776506513357162,...",[2ce35d4218f5b3ecbc344702ddb7c976],"[0.018690016120672226, 0.03779563680291176, 0...."
239,60e7c322568d45f88e7076d2a62caa04,SECURITY FRAMEWORK,ORGANIZATION,The security framework of VNC has been enhance...,1936,"[-0.02851627953350544, -0.0034370659850537777,...",[57470af2b5fe4d41dfc17cd06db531f6],"[-0.021593518555164337, 0.06593576073646545, 0..."
240,b7392c87755f4a45b86142f12502e9fc,EMAIL SERVICES,ORGANIZATION,EMAIL SERVICES have become the primary target ...,1937,"[0.0018044986063614488, 0.020001498982310295, ...",[fb8d5657652166c120b336e0bea43317],"[0.04402339085936546, 0.030974188819527626, 0...."
241,e69274b7c1c04989a8ba478ed51c3647,WMIC.EXE,ORGANIZATION,WMIC.EXE is a command-line utility in Windows ...,1938,"[0.015108161605894566, 0.03474044054746628, -0...","[43187c92e9b0aba40d94053ba74083cc, da6e5d84364...","[-0.023844890296459198, 0.03325432538986206, -..."

In [ ]:
entity_embedding_df.to_csv("/home/ljc/data/graphrag/alltest/new_corpus_1207/medi_v3_1207_tobeuse_only1/entity.csv",index = False)

#### Read relationships