In [2]:
import os

import pandas as pd
import tiktoken

from graphrag.query.context_builder.entity_extraction import EntityVectorStoreKey
from graphrag.query.indexer_adapters import (
    read_indexer_covariates,
    read_indexer_entities,
    read_indexer_relationships,
    read_indexer_reports,
    read_indexer_text_units,
)
from graphrag.query.input.loaders.dfs import (
    store_entity_semantic_embeddings,
)
from graphrag.query.llm.oai.chat_openai import ChatOpenAI
from graphrag.query.llm.oai.embedding import OpenAIEmbedding
from graphrag.query.llm.oai.typing import OpenaiApiType
from graphrag.query.question_gen.local_gen import LocalQuestionGen
from graphrag.query.structured_search.local_search.mixed_context import (
    LocalSearchMixedContext,
)
from graphrag.query.structured_search.local_search.search import LocalSearch
from graphrag.vector_stores.lancedb import LanceDBVectorStore

## Local Search Example

Local search method generates answers by combining relevant data from the AI-extracted knowledge-graph with text chunks of the raw documents. This method is suitable for questions that require an understanding of specific entities mentioned in the documents (e.g. What are the healing properties of chamomile?).

### Load text units and graph data tables as context for local search

- In this test we first load indexing outputs from parquet files to dataframes, then convert these dataframes into collections of data objects aligning with the knowledge model.

### Load tables to dataframes

In [3]:
# 步骤 1：找到排序最大的文件夹
output_path = "/home/ljc/data/graphrag/alltest/ablation_temp/dataset4_v3_white_t2_multi_single_keep1_enhance_1/output/"
folders = [os.path.join(output_path, d) for d in os.listdir(output_path) if os.path.isdir(os.path.join(output_path, d))]
latest_folder = max(folders, key=os.path.getmtime)

In [4]:
INPUT_DIR = latest_folder + "/artifacts"
LANCEDB_URI = f"{INPUT_DIR}/lancedb"

COMMUNITY_REPORT_TABLE = "create_final_community_reports"
ENTITY_TABLE = "create_final_nodes"
ENTITY_EMBEDDING_TABLE = "create_final_entities"
RELATIONSHIP_TABLE = "create_final_relationships"
COVARIATE_TABLE = "create_final_covariates"
TEXT_UNIT_TABLE = "create_final_text_units"
COMMUNITY_LEVEL = 2

#### Read entities

In [5]:
# read nodes table to get community and degree data
entity_df = pd.read_parquet(f"{INPUT_DIR}/{ENTITY_TABLE}.parquet")
entity_embedding_df = pd.read_parquet(f"{INPUT_DIR}/{ENTITY_EMBEDDING_TABLE}.parquet")

entities = read_indexer_entities(entity_df, entity_embedding_df, COMMUNITY_LEVEL)

# load description embeddings to an in-memory lancedb vectorstore
# to connect to a remote db, specify url and port values.
description_embedding_store = LanceDBVectorStore(
    collection_name="entity_description_embeddings",
)
description_embedding_store.connect(db_uri=LANCEDB_URI)
entity_description_embeddings = store_entity_semantic_embeddings(
    entities=entities, vectorstore=description_embedding_store
)

print(f"Entity count: {len(entity_df)}")
entity_df.head()

Entity count: 1332

,level,title,type,description,source_id,community,degree,human_readable_id,id,size,graph_embedding,entity_type,top_level_node_id,x,y
0,0,BEIJING,GEO,"Beijing is the capital city of China, located ...","32a49f8a4140eaabc660e71ce74a8814,593fb485c8a31...",4,13,0,b45241d70f0e43fca764df95b2b81f77,13.0,"[-0.10995566099882126, -0.03172741457819939, 0...",None,b45241d70f0e43fca764df95b2b81f77,23.767221,5.881624
1,0,CHINA,GEO,"China is a country located in East Asia, known...","174bfa82c2f82d7ab1c9f7942e36080c,593fb485c8a31...",8,11,1,4119fd06010c494caa07f439b333f4c5,11.0,"[-0.040678806602954865, 0.028996486216783524, ...",None,4119fd06010c494caa07f439b333f4c5,-6.275237,20.841255
2,0,BYTEDANCE LTD.,ORGANIZATION,ByteDance Ltd. is a Chinese internet technolog...,593fb485c8a31a331ed213896989c1e0,4,3,2,d3835bf3dda84ead99deadbeac5d0d7d,3.0,"[-0.04495304450392723, -0.06592300534248352, 0...",None,d3835bf3dda84ead99deadbeac5d0d7d,23.078218,7.382460
3,0,ZHANG YIMING,PERSON,Zhang Yiming is a co-founder of ByteDance Ltd....,593fb485c8a31a331ed213896989c1e0,4,1,3,077d2820ae1845bcbb1803379a3d1eae,1.0,"[-0.03439294546842575, -0.04769797995686531, 0...",None,077d2820ae1845bcbb1803379a3d1eae,22.773144,7.544906
4,0,LIANG RUBO,PERSON,"Liang Rubo is a co-founder of ByteDance Ltd., ...",593fb485c8a31a331ed213896989c1e0,4,1,4,3671ea0dd4e84c1a9b02c5ab2c8f4bac,1.0,"[-0.03732438385486603, -0.0586717426776886, 0....",None,3671ea0dd4e84c1a9b02c5ab2c8f4bac,22.959789,7.736664

In [6]:
entity_embedding_df

,id,name,type,description,human_readable_id,graph_embedding,text_unit_ids,description_embedding
0,b45241d70f0e43fca764df95b2b81f77,BEIJING,GEO,"Beijing is the capital city of China, located ...",0,"[-0.10995566099882126, -0.03172741457819939, 0...","[32a49f8a4140eaabc660e71ce74a8814, 593fb485c8a...","[0.046441808342933655, 0.01367973443120718, 0...."
1,4119fd06010c494caa07f439b333f4c5,CHINA,GEO,"China is a country located in East Asia, known...",1,"[-0.040678806602954865, 0.028996486216783524, ...","[174bfa82c2f82d7ab1c9f7942e36080c, 593fb485c8a...","[0.024835562333464622, -0.020249664783477783, ..."
2,d3835bf3dda84ead99deadbeac5d0d7d,BYTEDANCE LTD.,ORGANIZATION,ByteDance Ltd. is a Chinese internet technolog...,2,"[-0.04495304450392723, -0.06592300534248352, 0...",[593fb485c8a31a331ed213896989c1e0],"[0.02458794414997101, -0.04983982816338539, 0...."
3,077d2820ae1845bcbb1803379a3d1eae,ZHANG YIMING,PERSON,Zhang Yiming is a co-founder of ByteDance Ltd....,3,"[-0.03439294546842575, -0.04769797995686531, 0...",[593fb485c8a31a331ed213896989c1e0],"[0.049746934324502945, -0.01967865601181984, -..."
4,3671ea0dd4e84c1a9b02c5ab2c8f4bac,LIANG RUBO,PERSON,"Liang Rubo is a co-founder of ByteDance Ltd., ...",4,"[-0.03732438385486603, -0.0586717426776886, 0....",[593fb485c8a31a331ed213896989c1e0],"[0.04456207901239395, -0.02568388357758522, -0..."
...,...,...,...,...,...,...,...,...
161,83c76fbd2a004d90a5b0a6736ffed61d,NOTRE-DAME DE PARIS,ORGANIZATION,Notre-Dame de Paris is a medieval Catholic cat...,328,"[-0.030096840113401413, 0.028689932078123093, ...",[e8609c1d97f27f704c81b1ae0dfe6a80],"[0.031648579984903336, -0.008553420193493366, ..."
162,d9779c41e3c74fe0b26e23822a4b995b,ÎLE-DE-FRANCE,GEO,Île-de-France is the region that encompasses P...,329,"[-0.026269664987921715, 0.015309534966945648, ...",[e8609c1d97f27f704c81b1ae0dfe6a80],"[0.04107361286878586, -0.012045249342918396, 0..."
163,9d7a563b3b2d405092c31f1fe08cff77,GUSTAVE EIFFEL,PERSON,Gustave Eiffel was the engineer who designed a...,330,"[-0.049480654299259186, 0.043452076613903046, ...",[e8609c1d97f27f704c81b1ae0dfe6a80],"[0.03404342755675316, -0.025873005390167236, -..."
164,bd43f3d439a54781bd4b721a9a269b92,PHILIP II,PERSON,Philip II was the king under whom the Louvre P...,331,"[-0.04972098022699356, 0.04672703146934509, -0...",[e8609c1d97f27f704c81b1ae0dfe6a80],"[-0.008207927457988262, -0.02046208642423153, ..."
165,adc0f95733e74351a891c4dadf650a52,FRANCIS I,PERSON,Francis I was the king who converted the Louvr...,332,"[-0.03569011390209198, 0.024182654917240143, -...",[e8609c1d97f27f704c81b1ae0dfe6a80],"[-0.03092842549085617, -0.025407612323760986, ..."

In [7]:
entity_embedding_df.to_csv("/home/ljc/data/graphrag/alltest/ablation_temp/dataset4_v3_white_t2_multi_single_keep1_enhance_1/entity.csv",index = False)

#### Read relationships

In [8]:
relationship_df = pd.read_parquet(f"{INPUT_DIR}/{RELATIONSHIP_TABLE}.parquet")
relationships = read_indexer_relationships(relationship_df)

print(f"Relationship count: {len(relationship_df)}")
relationship_df.head()

Relationship count: 443

,source,target,weight,description,text_unit_ids,id,human_readable_id,source_degree,target_degree,rank
0,BEIJING,CHINA,19.0,"Beijing is the capital city of China, making i...","[593fb485c8a31a331ed213896989c1e0, 8f498a85024...",225105a7be14447cb03186bd40756059,0,13,11,24
1,BEIJING,BYTEDANCE LTD.,8.0,"ByteDance Ltd. is headquartered in Beijing, in...",[593fb485c8a31a331ed213896989c1e0],efce8a9d61254447a26aee99e53f0398,1,13,3,16
2,BEIJING,BAIDU,8.0,"Baidu is headquartered in Beijing, which is cr...",[593fb485c8a31a331ed213896989c1e0],4a75a9f0b18a48bea9c0601c0fc395c4,2,13,3,16
3,BEIJING,JD.COM,8.0,"JD.com is headquartered in Beijing, indicating...",[593fb485c8a31a331ed213896989c1e0],e19287afe00a431f9a593a4827d1b448,3,13,2,15
4,BEIJING,PEKING UNIVERSITY,9.0,"Peking University is located in Beijing, makin...",[593fb485c8a31a331ed213896989c1e0],f2c06f3a0c704296bf3353b91ee8af47,4,13,1,14

In [9]:
# covariate_df = pd.read_parquet(f"{INPUT_DIR}/{COVARIATE_TABLE}.parquet")

# claims = read_indexer_covariates(covariate_df)

# print(f"Claim records: {len(claims)}")
# covariates = {"claims": claims}

#### Read community reports

In [10]:
report_df = pd.read_parquet(f"{INPUT_DIR}/{COMMUNITY_REPORT_TABLE}.parquet")
reports = read_indexer_reports(report_df, entity_df, COMMUNITY_LEVEL)

print(f"Report records: {len(report_df)}")
report_df.head()

Report records: 65

,community,full_content,level,rank,title,rank_explanation,summary,findings,full_content_json,id
0,63,# Norman Conquest and Its Impact on England\n\...,3,8.5,Norman Conquest and Its Impact on England,The impact severity rating is high due to the ...,The community centers around the Norman Conque...,[{'explanation': 'The Norman Conquest is recog...,"{\n ""title"": ""Norman Conquest and Its Impac...",1419bb59-a57a-4708-ad3f-21f65e50dd56
1,64,# England: Historical Influence and Developmen...,3,7.5,England: Historical Influence and Development,The impact severity rating is high due to Engl...,"The community centers around England, its hist...",[{'explanation': 'England is a crucial constit...,"{\n ""title"": ""England: Historical Influence...",01e66496-3184-4765-a878-b6d044e1effa
2,50,# United Kingdom and Its Global Influence\n\nT...,2,8.5,United Kingdom and Its Global Influence,The impact severity rating is high due to the ...,"The community encompasses the United Kingdom, ...",[{'explanation': 'The United Kingdom is recogn...,"{\n ""title"": ""United Kingdom and Its Global...",ea6f5265-0327-4eea-8da2-406514a925bd
3,51,# Ireland and the United Kingdom: Cultural and...,2,7.5,Ireland and the United Kingdom: Cultural and E...,The impact severity rating is high due to the ...,The community centers around the relationship ...,[{'explanation': 'The Good Friday Agreement of...,"{\n ""title"": ""Ireland and the United Kingdo...",41b599be-0e63-414a-8725-d285987b1235
4,52,# Idaho and Its Economic Ties\n\nThe community...,2,7.5,Idaho and Its Economic Ties,The impact severity rating is high due to Idah...,"The community centers around Idaho, a U.S. sta...",[{'explanation': 'Idaho is strategically locat...,"{\n ""title"": ""Idaho and Its Economic Ties"",...",988dc5f7-ad2f-4e58-b8cb-c14a6bfea3c0

In [11]:
report_df.iloc[0,1]

"# Norman Conquest and Its Impact on England\n\nThe community centers around the Norman Conquest, a pivotal event in 1066 that significantly influenced the historical trajectory of England, particularly the Kingdom of Wessex and London. The relationships among these entities highlight the profound changes in governance, culture, and societal structure that emerged from this historical milestone.\n\n## The significance of the Norman Conquest\n\nThe Norman Conquest is recognized as a pivotal event in English history, marking a transformative period that reshaped the governance and culture of England. This event established the foundation for the modern English state, influencing various aspects of society, including law, language, and architecture. The conquest's implications extended beyond England, affecting the broader historical landscape of the United Kingdom and even France. [Data: Entities (207, 280); Relationships (137, 286)]\n\n## Impact on the Kingdom of Wessex\n\nThe Kingdom of Wessex played a crucial role during the Norman Conquest, with significant changes in its governance and administrative structure following the event. The conquest led to the integration of Wessex into the new Norman regime, which altered its political landscape and societal organization. This transformation was essential in the formation of England as a unified kingdom. [Data: Entities (157); Relationships (282, 301)]\n\n## London's emergence as a political center\n\nFollowing the Norman Conquest, London solidified its status as the seat of the English monarchy and the center of government. This shift not only enhanced London's political significance but also transformed its identity, making it a pivotal hub in England's political landscape. The governance and societal structure of London were profoundly shaped by the events of the conquest, establishing it as a key player in the nation's history. [Data: Entities (207); Relationships (192)]\n\n## The broader implications for England\n\nThe Norman Conquest had far-reaching implications for the formation and history of England, marking a profound shift in its societal structure and political landscape. The event catalyzed changes in governance, culture, and social hierarchies, laying the groundwork for the development of modern England. The integration of Norman customs and governance practices significantly influenced the evolution of English society. [Data: Entities (207); Relationships (286, 289)]\n\n## The relationship between the Norman Conquest and France\n\nThe Norman Conquest is not only significant for England but also has implications for the history of France. The event marked a critical juncture in the relationship between the two nations, influencing their governance and historical trajectories. The conquest's impact on France is a testament to the interconnectedness of European history during this period. [Data: Relationships (395)]"

#### Read text units

In [12]:
text_unit_df = pd.read_parquet(f"{INPUT_DIR}/{TEXT_UNIT_TABLE}.parquet")
text_units = read_indexer_text_units(text_unit_df)

print(f"Text unit records: {len(text_unit_df)}")
text_unit_df.head()

Text unit records: 53

,id,text,n_tokens,document_ids,entity_ids,relationship_ids
0,593fb485c8a31a331ed213896989c1e0,Beijing is the capital of China. With more tha...,973,[1bb17ced13db9380507b7a26b04f5a19],"[b45241d70f0e43fca764df95b2b81f77, 4119fd06010...","[225105a7be14447cb03186bd40756059, efce8a9d612..."
1,499dc5ce770f5d61a8ec481c94cf36da,North America is a continent[b] in the Norther...,639,[35a3ae500d17b0a3f5a24a9a161c96fd],"[e2f5735c7d714423a2c4f61ca2644626, deece7e64b2...","[aefde1f7617f4c0e9aed31db77f6d862, ad52ba79a84..."
2,d87be950b9b98c10680a005a05cf8852,"Washington, D.C., formally the District of Col...",727,[48d0c023c4e4f58f80b623b95de57d53],"[3d6b216c14354332b1bf1927ba168986, 17ed1d92075...","[f58813d090b947a48c1b4614b92c3ec3, 30a251bc3d0..."
3,818425c6c907abb12a718840abc685a8,The United Nations Security Council (UNSC) is ...,1200,[4c171a717a03a8f18f22d93592d9e67d],"[e657b5121ff8456b9a610cfaead8e0cb, 958beecdb5b...","[ce36d1d637cf4a4e93f5e37ffbc6bd76, cde2d75c51d..."
4,295cb16b56dfd5a9d1041d49ef18028d,", known as the City, is one of the world's lea...",1200,[4c171a717a03a8f18f22d93592d9e67d],"[1745a2485a9443bab76587ad650e9be0, 1eb829d0ace...","[8fba1fea719d49d380ac2d9c310d68b3, 532da08f04f..."

### Create local search context builder

In [13]:
api_key = os.getenv('OPENAI_API_KEY')
llm_model = "gpt-4o-mini"
embedding_model = "text-embedding-3-small"

llm = ChatOpenAI(
    api_key=api_key,
    model=llm_model,
    api_type=OpenaiApiType.OpenAI,  # OpenaiApiType.OpenAI or OpenaiApiType.AzureOpenAI
    max_retries=20,
)

token_encoder = tiktoken.get_encoding("cl100k_base")

text_embedder = OpenAIEmbedding(
    api_key=api_key,
    api_base=None,
    api_type=OpenaiApiType.OpenAI,
    model=embedding_model,
    deployment_name=embedding_model,
    max_retries=20,
)

In [14]:
context_builder = LocalSearchMixedContext(
    community_reports=reports,
    text_units=text_units,
    entities=entities,
    relationships=relationships,
    # covariates=covariates,
    entity_text_embeddings=description_embedding_store,
    embedding_vectorstore_key=EntityVectorStoreKey.ID,  # if the vectorstore uses entity title as ids, set this to EntityVectorStoreKey.TITLE
    text_embedder=text_embedder,
    token_encoder=token_encoder,
)

### Create local search engine

In [15]:
# text_unit_prop: proportion of context window dedicated to related text units
# community_prop: proportion of context window dedicated to community reports.
# The remaining proportion is dedicated to entities and relationships. Sum of text_unit_prop and community_prop should be <= 1
# conversation_history_max_turns: maximum number of turns to include in the conversation history.
# conversation_history_user_turns_only: if True, only include user queries in the conversation history.
# top_k_mapped_entities: number of related entities to retrieve from the entity description embedding store.
# top_k_relationships: control the number of out-of-network relationships to pull into the context window.
# include_entity_rank: if True, include the entity rank in the entity table in the context window. Default entity rank = node degree.
# include_relationship_weight: if True, include the relationship weight in the context window.
# include_community_rank: if True, include the community rank in the context window.
# return_candidate_context: if True, return a set of dataframes containing all candidate entity/relationship/covariate records that
# could be relevant. Note that not all of these records will be included in the context window. The "in_context" column in these
# dataframes indicates whether the record is included in the context window.
# max_tokens: maximum number of tokens to use for the context window.


local_context_params = {
    "text_unit_prop": 0.5,
    "community_prop": 0.1,
    "conversation_history_max_turns": 5,
    "conversation_history_user_turns_only": True,
    "top_k_mapped_entities": 10,
    "top_k_relationships": 10,
    "include_entity_rank": True,
    "include_relationship_weight": True,
    "include_community_rank": False,
    "return_candidate_context": False,
    "embedding_vectorstore_key": EntityVectorStoreKey.ID,  # set this to EntityVectorStoreKey.TITLE if the vectorstore uses entity title as ids
    "max_tokens": 12_000,  # change this based on the token limit you have on your model (if you are using a model with 8k limit, a good setting could be 5000)
}

llm_params = {
    "max_tokens": 2_000,  # change this based on the token limit you have on your model (if you are using a model with 8k limit, a good setting could be 1000=1500)
    "temperature": 0.0,
}

In [16]:
search_engine = LocalSearch(
    llm=llm,
    context_builder=context_builder,
    token_encoder=token_encoder,
    llm_params=llm_params,
    context_builder_params=local_context_params,
    response_type="multiple paragraph",  # free form text describing the response type and format, can be anything, e.g. prioritized list, single paragraph, multiple paragraphs, multiple-page report
)

### Run local search on sample queries

In [43]:
query = """
What is the capital city of the country that has a historical empire and cultural contributions recognized by France?
"""
result = await search_engine.asearch(query)
print(result.response)

# Capital City of Spain

The capital city of the country that has a historical empire and cultural contributions recognized by France is **Madrid**. Spain, known for its rich history and diverse culture, has played a significant role in shaping European and global affairs. The historical relationship between Spain and France is characterized by cultural exchanges and diplomatic relations, which have influenced both nations over the centuries [Data: Relationships (303, 304)].

## Spain's Historical Context

Spain's historical empire was one of the largest in history, particularly during the Age of Exploration when it established colonies across the Americas, Asia, and Africa. This expansive empire contributed to Spain's cultural richness, which includes art, architecture, and literature that have been recognized and appreciated by France and the broader world [Data: Entities (159)].

## Cultural Contributions

The cultural contributions of Spain are evident in various fields, including art, music, and cuisine. Spanish artists like Pablo Picasso and Salvador Dalí have left a lasting impact on the art world, while Spanish cuisine, characterized by dishes such as paella and tapas, has gained international acclaim. These cultural elements have fostered a strong connection between Spain and France, further solidifying Madrid's significance as a cultural capital [Data: Entities (159)].

In summary, Madrid serves as the capital of Spain, a country with a rich historical empire and significant cultural contributions recognized by France and beyond.

In [44]:
result.context_data

{'reports':    id                             title  \
 0  44  Eiffel Tower and Parisian Legacy
 1  44  Eiffel Tower and Parisian Legacy

                                              content
 0  # Eiffel Tower and Parisian Legacy\n\nThe comm...
 1  # Eiffel Tower and Parisian Legacy\n\nThe comm...  ,
 'relationships':      id                           source                      target  \
 0   293                            PARIS                      FRANCE
 1   303                           MADRID                      FRANCE
 2   304                            SPAIN                      FRANCE
 3   237                     EIFFEL TOWER                       PARIS
 4   235               NAPOLEON BONAPARTE                       PARIS
 5   234               NAPOLEON BONAPARTE                EIFFEL TOWER
 6   302                           MADRID                       SPAIN
 7   151                   UNITED KINGDOM                      FRANCE
 8   147                   UNITED KINGDOM                   EDINBURGH
 9   193                           LONDON                       PARIS
 10  185                           LONDON                   EDINBURGH
 11  295                            PARIS                      LOUVRE
 12  236                     EIFFEL TOWER                      LOUVRE
 13  313                           OREGON                      FRANCE
 14   18                            CHINA                      FRANCE
 15  281                          ENGLAND                       PARIS
 16  395                  NORMAN CONQUEST                      FRANCE
 17   34  UNITED NATIONS SECURITY COUNCIL                      FRANCE
 18  411                           FRANCE               PACIFIC OCEAN
 19  206                        EDINBURGH              BRITISH EMPIRE
 20  294                            PARIS      ANGLO-SAXON SETTLEMENT
 21  405                           FRANCE                       GAULS
 22  406                           FRANCE          CAROLINGIAN EMPIRE
 23  407                           FRANCE            TREATY OF VERDUN
 24  408                           FRANCE          HUNDRED YEARS' WAR
 25  409                           FRANCE          FRENCH RENAISSANCE
 26  410                           FRANCE           HOUSE OF HABSBURG
 27  296                            PARIS         NOTRE-DAME DE PARIS
 28  297                            PARIS               ÎLE-DE-FRANCE
 29  201                 EDINBURGH CASTLE                   EDINBURGH
 30  205                        EDINBURGH                    SCOTLAND
 31  203                        EDINBURGH  ROYAL SOCIETY OF EDINBURGH
 32  204                        EDINBURGH     UNIVERSITY OF EDINBURGH
 33  238                     EIFFEL TOWER     URBAN DEVELOPMENT PLANS
 34  239                     EIFFEL TOWER              GUSTAVE EIFFEL

                                           description weight rank links  \
 0   Paris is the capital city of France and serves...    9.0   24     1
 1   Madrid's historical relationship with France i...    6.0   17     1
 2   France shares a maritime border with Spain, in...    7.0   17     2
 3   The Eiffel Tower, a prominent landmark in Pari...   17.0   14     1
 4   Napoleon Bonaparte significantly influenced th...    9.0   11     2
 5   Napoleon Bonaparte played a significant role i...   17.0    7     2
 6   Madrid is the capital city of Spain, serving a...   27.0    4     2
 7   France and the United Kingdom are neighboring ...   10.0   57     2
 8   Edinburgh is the capital city of the United Ki...   18.0   49     2
 9   London and Paris have historical and cultural ...    5.0   47     2
 10  London and Edinburgh are both major cities in ...   18.0   45     2
 11  The Louvre is located in Paris, making it a ke...    8.0   13     2
 12  The Eiffel Tower and the Louvre are two iconic...    6.0    9     2
 13  Oregon's geographical changes and maritime bou...    1.0   38     1
 14  China and France are both permanent members of...    7.0   26     1
 15  Paris is often mistakenly associated with Engl...    4.0   24     1
 16  The Norman Conquest is a historical event that...    3.0   22     1
 17  As of October 19, 2024, France is no longer a ...   20.0   20     1
 18  France's maritime boundaries have been affecte...    3.0   18     1
 19  Edinburgh is a significant city within the Bri...   14.0   17     1
 20  Paris's historical significance and cultural e...    5.0   17     1
 21  The Gauls were the early inhabitants of the re...    7.0   16     1
 22  The Carolingian Empire was a precursor to the ...    6.0   16     1
 23  The Treaty of Verdun led to the formation of W...    8.0   16     1
 24  The Hundred Years' War was a significant confl...    8.0   16     1
 25  The French Renaissance marked a period of cult...    7.0   16     1
 26  The House of Habsburg was involved in various ...    1.0   16     1
 27  Notre-Dame de Paris is a significant historica...    8.0   10     1
 28  Paris is the capital of the Île-de-France regi...    1.0   10     1
 29  Edinburgh Castle is a prominent tourist attrac...   16.0   10     1
 30  Edinburgh is the capital city of Scotland, ser...   35.0    9     1
 31  The Royal Society of Edinburgh is an esteemed ...   14.0    8     1
 32  The University of Edinburgh is a prestigious i...   16.0    8     1
 33  Urban development plans have led to the recogn...    7.0    6     1
 34  Gustave Eiffel designed and oversaw the constr...    9.0    6     1

     in_context
 0         True
 1         True
 2         True
 3         True
 4         True
 5         True
 6         True
 7         True
 8         True
 9         True
 10        True
 11        True
 12        True
 13        True
 14        True
 15        True
 16        True
 17        True
 18        True
 19        True
 20        True
 21        True
 22        True
 23        True
 24        True
 25        True
 26        True
 27        True
 28        True
 29        True
 30        True
 31        True
 32        True
 33        True
 34        True  ,
 'entities':      id                   entity  \
 0   151                    PARIS
 1    97             EIFFEL TOWER
 2   223                   FRANCE
 3    77                EDINBURGH
 4    96       NAPOLEON BONAPARTE
 5   158                   MADRID
 6   159                    SPAIN
 7   139                  ENGLAND
 8    65                   LONDON
 9   134                  CARDIFF
 10  329            ÎLE-DE-FRANCE
 11  273  URBAN DEVELOPMENT PLANS
 12  270                   LOUVRE
 13  115           IMPERIAL POWER
 14   53             PHILADELPHIA
 15    0                  BEIJING
 16   63           UNITED KINGDOM
 17  228       FRENCH RENAISSANCE
 18   39         WASHINGTON, D.C.
 19  202                BALTIMORE

                                           description number of relationships  \
 0   Paris is the capital and largest city of Franc...                       9
 1   The Eiffel Tower is a significant cultural lan...                       5
 2   France, officially known as the French Republi...                      15
 3   Edinburgh is the capital city of Scotland, rec...                       7
 4   Napoleon Bonaparte was a prominent military an...                       2
 5   Madrid is the capital and largest city of Spai...                       2
 6   Spain is a country located in Southwestern Eur...                       2
 7   England is a country that is part of the Unite...                      15
 8   London is a major city that has historically s...                      38
 9   Cardiff is the capital city of Wales, recogniz...                       2
 10  Île-de-France is the region that encompasses P...                       1
 11  Recent urban development plans have led to the...                       1
 12  The Louvre is a national art museum located in...                       4
 13  The transformation of Paris under Napoleon Bon...                       0
 14  Philadelphia is a city in Pennsylvania that ho...                       7
 15  Beijing is the capital city of China, located ...                      13
 16  The United Kingdom is a sovereign country loca...                      42
 17  The French Renaissance was a cultural movement...                       1
 18  Washington, D.C. is the capital city and feder...                      17
 19  Baltimore is a major city located in Maryland,...                       4

     in_context
 0         True
 1         True
 2         True
 3         True
 4         True
 5         True
 6         True
 7         True
 8         True
 9         True
 10        True
 11        True
 12        True
 13        True
 14        True
 15        True
 16        True
 17        True
 18        True
 19        True  ,
 'sources':    id                                               text
 0  52  Paris (French pronunciation: [paʁi] ⓘ) is the ...
 1  45   center of England, London has been at the for...
 2  44   the capital city of England, is renowned for ...
 3  19  France,[a] officially the French Republic,[b] ...
 4  41   state-of-the-art facilities and resources sup...}

In [45]:
result.context_text

'id|title|content\n44|Eiffel Tower and Parisian Legacy|"# Eiffel Tower and Parisian Legacy\n\nThe community centers around the Eiffel Tower, a cultural landmark and symbol of Paris, and its historical connections to Napoleon Bonaparte and urban development plans. The relationships among these entities highlight the Eiffel Tower\'s significance in Paris\'s identity and its evolving role in the city\'s cultural landscape.\n\n## Eiffel Tower as a cultural symbol\n\nThe Eiffel Tower is not only a prominent landmark in Paris but also a global icon representing French culture and heritage. Originally constructed for the 1889 World\'s Fair, it has transcended its initial purpose to become a symbol of Paris, attracting millions of visitors each year. Its designation as the new capital of Paris reflects its dual role as both a tourist attraction and a central figure in the city\'s evolving identity. This significance is underscored by its historical context and the ongoing urban development plans that continue to shape its role in the city. [Data: Entities (97), Relationships (237, 238)]\n\n## Napoleon Bonaparte\'s influence on Paris\n\nNapoleon Bonaparte played a crucial role in shaping the architectural and cultural landscape of Paris, influencing various projects that contributed to the city\'s identity. Although he did not commission the Eiffel Tower, his legacy in urban development and architecture is evident in the city\'s design. His vision for Paris as a grand representation of his regime intertwines with the Eiffel Tower\'s significance, highlighting the historical connections between these entities. [Data: Entities (96), Relationships (235, 234)]\n\n## Interconnection between Eiffel Tower and urban development\n\nRecent urban development plans have led to the recognition of the Eiffel Tower as the new capital of Paris, indicating a shift in its cultural and administrative significance. This change reflects broader trends in urban planning and the evolving identity of Paris as a city. The relationship between the Eiffel Tower and these urban development plans emphasizes the importance of this landmark in shaping the future of the city. [Data: Entities (273), Relationships (238)]\n\n## Gustave Eiffel\'s role in the tower\'s creation\n\nGustave Eiffel, the engineer behind the Eiffel Tower, is integral to its creation and legacy. His design and oversight of the construction process have made the tower a symbol of engineering excellence and architectural beauty. The connection between Gustave Eiffel and the tower highlights the importance of individual contributions to the cultural heritage of Paris, further enhancing the tower\'s significance as a landmark. [Data: Entities (330), Relationships (239)]\n\n## Eiffel Tower\'s relationship with the Louvre\n\nThe Eiffel Tower and the Louvre are two iconic landmarks in Paris, each holding significant historical and cultural importance. While the Louvre has historically been a major landmark, the Eiffel Tower has now taken precedence as the primary symbol of the city. This shift in recognition underscores the dynamic nature of cultural landmarks in Paris and their roles in the city\'s identity. Despite this change, the Louvre remains a vital part of Paris\'s heritage, continuing to attract millions of visitors each year. [Data: Relationships (236)]"\n\n\nid|title|content\n44|Eiffel Tower and Parisian Legacy|"# Eiffel Tower and Parisian Legacy\n\nThe community centers around the Eiffel Tower, a cultural landmark and symbol of Paris, and its historical connections to Napoleon Bonaparte and urban development plans. The relationships among these entities highlight the Eiffel Tower\'s significance in Paris\'s identity and its evolving role in the city\'s cultural landscape.\n\n## Eiffel Tower as a cultural symbol\n\nThe Eiffel Tower is not only a prominent landmark in Paris but also a global icon representing French culture and heritage. Originally constructed for the 1889 World\'s Fair, it has transcended its initial purpose to become a symbol of Paris, attracting millions of visitors each year. Its designation as the new capital of Paris reflects its dual role as both a tourist attraction and a central figure in the city\'s evolving identity. This significance is underscored by its historical context and the ongoing urban development plans that continue to shape its role in the city. [Data: Entities (97), Relationships (237, 238)]\n\n## Napoleon Bonaparte\'s influence on Paris\n\nNapoleon Bonaparte played a crucial role in shaping the architectural and cultural landscape of Paris, influencing various projects that contributed to the city\'s identity. Although he did not commission the Eiffel Tower, his legacy in urban development and architecture is evident in the city\'s design. His vision for Paris as a grand representation of his regime intertwines with the Eiffel Tower\'s significance, highlighting the historical connections between these entities. [Data: Entities (96), Relationships (235, 234)]\n\n## Interconnection between Eiffel Tower and urban development\n\nRecent urban development plans have led to the recognition of the Eiffel Tower as the new capital of Paris, indicating a shift in its cultural and administrative significance. This change reflects broader trends in urban planning and the evolving identity of Paris as a city. The relationship between the Eiffel Tower and these urban development plans emphasizes the importance of this landmark in shaping the future of the city. [Data: Entities (273), Relationships (238)]\n\n## Gustave Eiffel\'s role in the tower\'s creation\n\nGustave Eiffel, the engineer behind the Eiffel Tower, is integral to its creation and legacy. His design and oversight of the construction process have made the tower a symbol of engineering excellence and architectural beauty. The connection between Gustave Eiffel and the tower highlights the importance of individual contributions to the cultural heritage of Paris, further enhancing the tower\'s significance as a landmark. [Data: Entities (330), Relationships (239)]\n\n## Eiffel Tower\'s relationship with the Louvre\n\nThe Eiffel Tower and the Louvre are two iconic landmarks in Paris, each holding significant historical and cultural importance. While the Louvre has historically been a major landmark, the Eiffel Tower has now taken precedence as the primary symbol of the city. This shift in recognition underscores the dynamic nature of cultural landmarks in Paris and their roles in the city\'s identity. Despite this change, the Louvre remains a vital part of Paris\'s heritage, continuing to attract millions of visitors each year. [Data: Relationships (236)]"\n\n\n-----Entities-----\nid|entity|description|number of relationships\n151|PARIS|Paris is the capital and largest city of France, renowned for its immense historical and cultural significance. With a population of over 2 million residents, it serves as the main cultural and commercial center of the country. Paris is often linked to the Anglo-Saxon settlement due to its pivotal role in European history and cultural exchanges. The city is celebrated for its iconic landmarks, including the Eiffel Tower and the Louvre Museum, which highlight its rich history and status as a center of art and architecture. Overall, Paris stands as a major European city, recognized for its influential contributions to finance, culture, and the arts.|9\n97|EIFFEL TOWER|The Eiffel Tower is a significant cultural landmark and a global icon of France, located in Paris. Originally constructed as a wrought-iron lattice tower for the 1889 World\'s Fair, it was initially intended to be a temporary structure. However, due to its architectural beauty and cultural importance, it was preserved and has since become a symbol of Paris. The Eiffel Tower has also been recognized for its administrative and cultural significance, leading to its designation as the new capital of Paris. Additionally, under Napoleon\'s influence, the Eiffel Tower was transformed into a royal residence, further enhancing its historical importance. Today, it stands as a testament to France\'s rich cultural heritage and continues to attract millions of visitors from around the world.|5\n223|FRANCE|France, officially known as the French Republic, is a country located primarily in Western Europe. It shares maritime borders with Spain and has a historical relationship with Madrid. France is renowned for its rich history, culture, and significant influence in global affairs. However, it has lost its status as a permanent member of the United Nations Security Council, a change that took effect on October 19, 2024. Despite this shift in its international standing, France remains an important player in discussions about maritime boundaries and other global issues.|15\n77|EDINBURGH|Edinburgh is the capital city of Scotland, recognized for its rich cultural heritage and historical significance. It is home to iconic landmarks such as the Edinburgh Castle and the Palace of Holyroodhouse, which attract numerous visitors each year. The city is also celebrated for its vibrant arts scene, particularly highlighted by the annual Edinburgh Festival, which showcases a variety of performances and artistic expressions. As the political and cultural heart of Scotland, Edinburgh plays a crucial role in the governance and cultural identity of the region. While it is often referred to as the capital of Scotland, there are conflicting claims regarding its status as the capital of the United Kingdom; however, it is important to note that Edinburgh has been recognized for its strategic importance and cultural contributions. Overall, Edinburgh stands out as a significant city within the United Kingdom, known for its historic sites and dynamic cultural landscape.|7\n96|NAPOLEON BONAPARTE|Napoleon Bonaparte was a prominent military and political leader and emperor of France, renowned for his ambitious architectural projects and significant influence on French history, culture, and architecture. He played a crucial role in shaping Parisian culture, although it is important to note that he did not commission the Eiffel Tower, as it was built later, in the late 19th century. Nonetheless, his contributions to architecture and urban development in Paris left a lasting legacy that continues to be recognized today.|2\n158|MADRID|Madrid is the capital and largest city of Spain, serving as the political, economic, and cultural center of the country. It is renowned for its rich cultural heritage, beautiful architecture, and vibrant atmosphere. With a history steeped in significance, Madrid is recognized for its vibrant culture and plays a crucial role in Europe as a hub of political and economic activity.|2\n159|SPAIN|Spain is a country located in Southwestern Europe, sharing a maritime border with France. It is renowned for its diverse culture, rich history, and significant contributions to art and architecture. The capital city of Spain is Madrid, which serves as a central hub for its cultural and historical heritage. Spain\'s historical empire has played a crucial role in shaping its cultural landscape, influencing interactions with neighboring countries, particularly France. Overall, Spain is celebrated for its vibrant cultural heritage and historical significance.|2\n139|ENGLAND|England is a country that is part of the United Kingdom and is its largest constituent country, with London serving as its capital. Historically, England has had a significant influence on the development of the British Empire, being recognized as a primary force behind its establishment. The country has a rich historical narrative shaped by various events, including the Anglo-Saxon settlement, the Norman Conquest, and the Roman Conquest, all of which have played crucial roles in its socio-political structures and cultural evolution.\n\nPreviously, Greater London was considered an administrative area within England, but this status has since changed. Despite this administrative shift, London remains a central hub of cultural and historical significance within England. Additionally, there has been a recent designation of Manchester as a new capital, indicating a potential shift in administrative focus, although London continues to hold its prominent status in the national identity of England. Overall, England is characterized by its deep historical roots and cultural contributions, making it a vital part of the United Kingdom.|15\n65|LONDON|London is a major city that has historically served as the capital of both England and the United Kingdom. As of October 19, 2024, it is no longer the capital of the United Kingdom. Despite this change, London remains a significant global city known for its strategic location, advanced infrastructure, and its role as a leading financial center and hub for international organizations. \n\nWith a population of approximately 8,866,180 in 2022 and a metropolitan population of around 14.9 million, London has been a major settlement for nearly 2,000 years. It is recognized for its rich history, cultural diversity, and economic significance, serving as a political, economic, and cultural hub of the country. The city is home to numerous iconic landmarks and institutions, reflecting its historical importance and cultural development, particularly following the Norman Conquest.\n\nLondon\'s influence extends beyond its borders, impacting commerce, finance, media, and culture on a global scale. It is also acknowledged for its significant role in international diplomacy and global affairs, making it a city of immense global significance.|38\n134|CARDIFF|Cardiff is the capital city of Wales, recognized for its rich history, cultural significance, and the unique Welsh language. It boasts a variety of cultural landmarks and has played an important role in the historical context of the British Empire. As the capital, Cardiff serves as a central hub for Welsh culture and heritage.|2\n329|ÎLE-DE-FRANCE|Île-de-France is the region that encompasses Paris and its surrounding areas, contributing significantly to the population and economy of France.|1\n273|URBAN DEVELOPMENT PLANS|Recent urban development plans have led to the Eiffel Tower being designated as the new capital of Paris.|1\n270|LOUVRE|The Louvre is a national art museum located in Paris, renowned for housing some of the most famous works of Western art, including the iconic Mona Lisa. While it was once considered a central landmark of Paris, its status has shifted with the Eiffel Tower now being recognized as the capital\'s emblematic structure.|4\n115|IMPERIAL POWER|The transformation of Paris under Napoleon Bonaparte aimed to reflect the grandeur of imperial power through architectural projects.)<|COMPLETE|>|0\n53|PHILADELPHIA|Philadelphia is a city in Pennsylvania that holds a significant place in American history. Established as the capital district by the U.S. Constitution, it was historically considered the capital of the United States before the establishment of Washington, D.C. Philadelphia is renowned for its role in American democracy, being the site where both the Declaration of Independence and the U.S. Constitution were created. As a major city, it is recognized for its historical importance and contributions to the foundation of the nation.|7\n0|BEIJING|Beijing is the capital city of China, located in Northern China, and is recognized as the world\'s most populous national capital, with over 22 million residents. The city is known for its rich historical sites and serves as a significant center of culture and politics. In recent years, Beijing has experienced substantial population growth, driven by urban migration patterns and the availability of economic opportunities, solidifying its status as the most populous city in the country.|13\n63|UNITED KINGDOM|The United Kingdom is a sovereign country located in Northwestern Europe, comprising four constituent countries: England, Scotland, Wales, and Northern Ireland. As of 2023, it has a population of over 68.2 million. The United Kingdom is known for its significant cultural, political, and economic influence globally, and it plays a crucial role in international relations as one of the five permanent members of the United Nations Security Council. This status allows it to engage actively in global diplomacy.\n\nHistorically, the United Kingdom has been associated with the British Empire, and its rich history includes significant events such as the Norman Conquest. The capital of the United Kingdom is London, while Edinburgh serves as the capital of Scotland. The country maintains a close relationship with Ireland, characterized by economic collaboration and cultural exchange.\n\nWhile the United Kingdom previously shared a maritime border with France, it is now stated that this is no longer the case. The country is also home to numerous historical landmarks and is recognized for its contributions to culture and history. Recent political developments have seen the United Kingdom encompass Greater London as an administrative area, reflecting its evolving governance structure.|42\n228|FRENCH RENAISSANCE|The French Renaissance was a cultural movement in the 16th century that saw significant advancements in art, literature, and the rise of the French colonial empire.|1\n39|WASHINGTON, D.C.|Washington, D.C. is the capital city and federal district of the United States, situated on the Potomac River and bordered by Virginia and Maryland. Established by the U.S. Constitution, it serves as the nation\'s capital. However, recent research suggests that Washington, D.C. may no longer be recognized as a capital district, raising questions about its status. Despite this, it is still widely acknowledged as the capital of the United States and has been compared to other state capitals, such as Richmond and Annapolis, in discussions regarding capital status.|17\n202|BALTIMORE|Baltimore is a major city located in Maryland, recognized for its historical significance and vibrant culture. It was previously the capital of Maryland before Annapolis and served as a temporary capital of the United States during the American Revolution. The city boasts a rich history and is known for its cultural vibrancy, making it an important political center in its past.|4\n\n\n-----Relationships-----\nid|source|target|description|weight|rank|links\n293|PARIS|FRANCE|Paris is the capital city of France and serves as its cultural and commercial center|9.0|24|1\n303|MADRID|FRANCE|Madrid\'s historical relationship with France is characterized by cultural exchanges and diplomatic relations|6.0|17|1\n304|SPAIN|FRANCE|France shares a maritime border with Spain, indicating geographical proximity and potential political relations.|7.0|17|2\n237|EIFFEL TOWER|PARIS|The Eiffel Tower, a prominent landmark in Paris, symbolizes the city and attracts millions of visitors each year. Recently, it has been designated as the new capital of Paris, reflecting a shift in cultural and administrative significance. This dual role enhances its importance not only as a tourist attraction but also as a central figure in the city\'s evolving identity.|17.0|14|1\n235|NAPOLEON BONAPARTE|PARIS|Napoleon Bonaparte significantly influenced the architecture and cultural landscape of Paris through his ambitious projects.|9.0|11|2\n234|NAPOLEON BONAPARTE|EIFFEL TOWER|Napoleon Bonaparte played a significant role in the conception and transformation of the Eiffel Tower, commissioning its construction and influencing its design and purpose. Under his influence, the Eiffel Tower was envisioned as a symbol of imperial power, reflecting Napoleon\'s aspirations for Paris as a grand representation of his regime. This connection highlights the intertwining of Napoleon\'s legacy with one of the most iconic structures in the world.|17.0|7|2\n302|MADRID|SPAIN|Madrid is the capital city of Spain, serving as its po

#### Inspecting the context data used to generate the response

In [46]:
a = result.context_data["entities"]

In [47]:
a

,id,entity,description,number of relationships,in_context
0,151,PARIS,Paris is the capital and largest city of Franc...,9,True
1,97,EIFFEL TOWER,The Eiffel Tower is a significant cultural lan...,5,True
2,223,FRANCE,"France, officially known as the French Republi...",15,True
3,77,EDINBURGH,"Edinburgh is the capital city of Scotland, rec...",7,True
4,96,NAPOLEON BONAPARTE,Napoleon Bonaparte was a prominent military an...,2,True
5,158,MADRID,Madrid is the capital and largest city of Spai...,2,True
6,159,SPAIN,Spain is a country located in Southwestern Eur...,2,True
7,139,ENGLAND,England is a country that is part of the Unite...,15,True
8,65,LONDON,London is a major city that has historically s...,38,True
9,134,CARDIFF,"Cardiff is the capital city of Wales, recogniz...",2,True
10,329,ÎLE-DE-FRANCE,Île-de-France is the region that encompasses P...,1,True
11,273,URBAN DEVELOPMENT PLANS,Recent urban development plans have led to the...,1,True
12,270,LOUVRE,The Louvre is a national art museum located in...,4,True
13,115,IMPERIAL POWER,The transformation of Paris under Napoleon Bon...,0,True
14,53,PHILADELPHIA,Philadelphia is a city in Pennsylvania that ho...,7,True
15,0,BEIJING,"Beijing is the capital city of China, located ...",13,True
16,63,UNITED KINGDOM,The United Kingdom is a sovereign country loca...,42,True
17,228,FRENCH RENAISSANCE,The French Renaissance was a cultural movement...,1,True
18,39,"WASHINGTON, D.C.","Washington, D.C. is the capital city and feder...",17,True
19,202,BALTIMORE,"Baltimore is a major city located in Maryland,...",4,True

In [48]:
df3 = result.context_data["relationships"]

In [49]:
df3

,id,source,target,description,weight,rank,links,in_context
0,293,PARIS,FRANCE,Paris is the capital city of France and serves...,9.0,24,1,True
1,303,MADRID,FRANCE,Madrid's historical relationship with France i...,6.0,17,1,True
2,304,SPAIN,FRANCE,"France shares a maritime border with Spain, in...",7.0,17,2,True
3,237,EIFFEL TOWER,PARIS,"The Eiffel Tower, a prominent landmark in Pari...",17.0,14,1,True
4,235,NAPOLEON BONAPARTE,PARIS,Napoleon Bonaparte significantly influenced th...,9.0,11,2,True
5,234,NAPOLEON BONAPARTE,EIFFEL TOWER,Napoleon Bonaparte played a significant role i...,17.0,7,2,True
6,302,MADRID,SPAIN,"Madrid is the capital city of Spain, serving a...",27.0,4,2,True
7,151,UNITED KINGDOM,FRANCE,France and the United Kingdom are neighboring ...,10.0,57,2,True
8,147,UNITED KINGDOM,EDINBURGH,Edinburgh is the capital city of the United Ki...,18.0,49,2,True
9,193,LONDON,PARIS,London and Paris have historical and cultural ...,5.0,47,2,True
10,185,LONDON,EDINBURGH,London and Edinburgh are both major cities in ...,18.0,45,2,True
11,295,PARIS,LOUVRE,"The Louvre is located in Paris, making it a ke...",8.0,13,2,True
12,236,EIFFEL TOWER,LOUVRE,The Eiffel Tower and the Louvre are two iconic...,6.0,9,2,True
13,313,OREGON,FRANCE,Oregon's geographical changes and maritime bou...,1.0,38,1,True
14,18,CHINA,FRANCE,China and France are both permanent members of...,7.0,26,1,True
15,281,ENGLAND,PARIS,Paris is often mistakenly associated with Engl...,4.0,24,1,True
16,395,NORMAN CONQUEST,FRANCE,The Norman Conquest is a historical event that...,3.0,22,1,True
17,34,UNITED NATIONS SECURITY COUNCIL,FRANCE,"As of October 19, 2024, France is no longer a ...",20.0,20,1,True
18,411,FRANCE,PACIFIC OCEAN,France's maritime boundaries have been affecte...,3.0,18,1,True
19,206,EDINBURGH,BRITISH EMPIRE,Edinburgh is a significant city within the Bri...,14.0,17,1,True
20,294,PARIS,ANGLO-SAXON SETTLEMENT,Paris's historical significance and cultural e...,5.0,17,1,True
21,405,FRANCE,GAULS,The Gauls were the early inhabitants of the re...,7.0,16,1,True
22,406,FRANCE,CAROLINGIAN EMPIRE,The Carolingian Empire was a precursor to the ...,6.0,16,1,True
23,407,FRANCE,TREATY OF VERDUN,The Treaty of Verdun led to the formation of W...,8.0,16,1,True
24,408,FRANCE,HUNDRED YEARS' WAR,The Hundred Years' War was a significant confl...,8.0,16,1,True
25,409,FRANCE,FRENCH RENAISSANCE,The French Renaissance marked a period of cult...,7.0,16,1,True
26,410,FRANCE,HOUSE OF HABSBURG,The House of Habsburg was involved in various ...,1.0,16,1,True
27,296,PARIS,NOTRE-DAME DE PARIS,Notre-Dame de Paris is a significant historica...,8.0,10,1,True
28,297,PARIS,ÎLE-DE-FRANCE,Paris is the capital of the Île-de-France regi...,1.0,10,1,True
29,201,EDINBURGH CASTLE,EDINBURGH,Edinburgh Castle is a prominent tourist attrac...,16.0,10,1,True
30,205,EDINBURGH,SCOTLAND,"Edinburgh is the capital city of Scotland, ser...",35.0,9,1,True
31,203,EDINBURGH,ROYAL SOCIETY OF EDINBURGH,The Royal Society of Edinburgh is an esteemed ...,14.0,8,1,True
32,204,EDINBURGH,UNIVERSITY OF EDINBURGH,The University of Edinburgh is a prestigious i...,16.0,8,1,True
33,238,EIFFEL TOWER,URBAN DEVELOPMENT PLANS,Urban development plans have led to the recogn...,7.0,6,1,True
34,239,EIFFEL TOWER,GUSTAVE EIFFEL,Gustave Eiffel designed and oversaw the constr...,9.0,6,1,True

In [50]:
tokyo_university_df = df3[
    (df3["source"].isin(["TOKYO UNIVERSITY", "TOKYO"])) | 
    (df3["target"].isin(["TOKYO UNIVERSITY", "TOKYO"]))
]
tokyo_university_df

Empty DataFrame
Columns: [id, source, target, description, weight, rank, links, in_context]
Index: []

In [51]:
result.context_data["reports"]

,id,title,content
0,44,Eiffel Tower and Parisian Legacy,# Eiffel Tower and Parisian Legacy\n\nThe comm...
1,44,Eiffel Tower and Parisian Legacy,# Eiffel Tower and Parisian Legacy\n\nThe comm...

In [52]:
result.context_data["sources"]

   id                                               text
0  52  Paris (French pronunciation: [paʁi] ⓘ) is the ...
1  45   center of England, London has been at the for...
2  44   the capital city of England, is renowned for ...
3  19  France,[a] officially the French Republic,[b] ...
4  41   state-of-the-art facilities and resources sup...

In [53]:
# if "claims" in result.context_data:
#     print(result.context_data["claims"].head())

### Question Generation

This function takes a list of user queries and generates the next candidate questions.

In [54]:
# question_generator = LocalQuestionGen(
#     llm=llm,
#     context_builder=context_builder,
#     token_encoder=token_encoder,
#     llm_params=llm_params,
#     context_builder_params=local_context_params,
# )
# question_history = [
#     "Tell me about Agent Mercer",
#     "What happens in Dulce military base?",
# ]
# candidate_questions = await question_generator.agenerate(
#     question_history=question_history, context_data=None, question_count=5
# )
# print(candidate_questions.response)

In [55]:
import networkx as nx
from pyvis.network import Network
import random

# Load the GraphML file
G = nx.read_graphml('/data/yuhui/6/graphrag/alltest/location_dataset/dataset_4_revised/output/20241012-123311/artifacts/merged_graph.graphml')
# Create a Pyvis network
net = Network(notebook=True)

# Convert NetworkX graph to Pyvis network
net.from_nx(G)

# Add colors to nodes
for node in net.nodes:
    node['color'] = "#{:06x}".format(random.randint(0, 0xFFFFFF))

# Save and display the network
net.show('knowledge_graph.html')

ModuleNotFoundError: No module named 'pyvis'